### PR TITLE
avoid ArrayIndexOutOfBoundsException for Stats in PrioritizedSplitRunner

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/prestosql/presto/issues/2981 (at least one symptom of it)

### CODE REVIEW

**Comment by sopel39** [comment]
please rebase instead of making merge commits

**Comment by tooptoop4** [comment]
@sopel39 rebased

**Comment by electrum** [comment]
Please update commit message to follow these guidelines: https://chris.beams.io/posts/git-commit/

In particular:

* Limit the subject line to 50 characters
* Capitalize the subject line

**Comment by electrum** [comment]
This looks like a bug in `TDigest`. We should fix the underlying bug rather than covering up the exception. cc @martint

**Comment by tooptoop4** [comment]
https://github.com/airlift/airlift/commit/0c5e482aeb708e280dbd61688a096a6d1053e5b8    https://github.com/airlift/airlift/commit/9e7e2e6a98cd6ed7e69854aa93b2fa875b8e7e7d should fix

**Pull request closed without merging**
