### PR TITLE
Enable LogTestDurationListener by default in GHA

### PR DESCRIPTION
**Pull request by kokosing**
Enable LogTestDurationListener by default in GHA

### CODE REVIEW

**Comment by losipiuk** [comment]
It does not support TestNG `@Factory` which I am using in https://github.com/prestosql/presto/pull/4998.

Will it be possible to disable the listener for `test-jdbc-compatibility ` by simply adding `-DLogTestDurationListener.enabled=false` to `MAVEN_OPTS`?

**Comment by kokosing** [comment]
> Will it be possible to disable the listener for test-jdbc-compatibility by simply adding -DLogTestDurationListener.enabled=false to MAVEN_OPTS?

Yes.

**Comment by kokosing** [comment]
> It does not support TestNG @Factory which I am using i

Can we fix that? What would be the outcome of lack of this support?

**Comment by losipiuk** [comment]
> > It does not support TestNG @factory which I am using i
> 
> Can we fix that? What would be the outcome of lack of this support?

Sure we can fix it. Yet in current state of the listener it will just throw if used with test classes using `@Factory`.
See:
https://github.com/prestosql/presto/blob/f7fc2951043da1cb38f73c315cd47d20312a0274/presto-testng-services/src/main/java/io/prestosql/testng/services/LogTestDurationListener.java#L194-L200

**Comment by kokosing** [comment]
> it will just throw

Then I guess we are good. As we will surely notice it and disable the listener

**Comment by losipiuk** [comment]
> > it will just throw
> 
> Then I guess we are good. As we will surely notice it and disable the listener

Thinking more - I am not sure what will be the result of this Listener throwing. Maybe it will just supress from execution all tests with `0` status code as we observed with `ReportUnannotatedMethods`. Could you wrap the execution `try-catch-all` in similar fashion we do in `ReportUnannotatedMethods`?

**Comment by kokosing** [comment]
> I am not sure what will be the result of this Listener throwing

Let see: https://github.com/prestosql/presto/pull/5007/commits/f2c416fb35fac19452679cfcf08404282c2e0107

**Comment by kokosing** [comment]
> I am not sure what will be the result of this Listener throwing

Surely, it was ignored.

**Review by losipiuk — APPROVED** [review]

**Comment by findepi** [comment]
> > I am not sure what will be the result of this Listener throwing
> 
> Surely, it was ignored.

See https://github.com/prestosql/presto/pull/4951
`LogTestDurationListener` should get updated too.

**Pull request merged**
