### PR TITLE
Fix flaky TestHttpRemoteTask#testDynamicFilters

### PR DESCRIPTION
**Pull request by sopel39**
Fixes: https://github.com/prestosql/presto/issues/5809

### CODE REVIEW

**Comment by findepi** [comment]
Thanks for fixing this. Can you add some comment what was broken?

**Comment by sopel39** [comment]
1. Timeout was apparently too short (5s)
2. Dynamic filter was updated before future was obtained, so future never completed, e.g:
```
        CompletableFuture<?> future = dynamicFilter.isBlocked();
        remoteTask.start();
        future.get();
```
this works, but:
```
        remoteTask.start();
        CompletableFuture<?> future = dynamicFilter.isBlocked();
        future.get();
```
might block forever

**Comment by findepi** [comment]
> but:
> 
> ```
>         remoteTask.start();
>         CompletableFuture<?> future = dynamicFilter.isBlocked();
>         future.get();
> ```
> 
> might block forever

oh, so it was a race condition?

why is the future not completed eventually, or returned a finished one if it was not going to be "more complete" ever?

**Review by findepi — APPROVED** [review]

**Comment by sopel39** [comment]
> why is the future not completed eventually, or returned a finished one if it was not going to be "more complete" ever?

it was not going to be more complete, because that was done only later in the test (but it never reached it because of block)

**Comment by phd3** [comment]
Observed this on #6602 again

```
2021-01-14T19:36:20.5681855Z [ERROR] testDynamicFilters(io.trino.server.remotetask.TestHttpRemoteTask)  Time elapsed: 0.755 s  <<< FAILURE!
2021-01-14T19:36:20.5687538Z java.lang.AssertionError: expected [2] but found [3]
2021-01-14T19:36:20.5691822Z 	at org.testng.Assert.fail(Assert.java:94)
2021-01-14T19:36:20.5696830Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2021-01-14T19:36:20.5702008Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2021-01-14T19:36:20.5707163Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2021-01-14T19:36:20.5712253Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2021-01-14T19:36:20.5717313Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2021-01-14T19:36:20.5726124Z 	at io.trino.server.remotetask.TestHttpRemoteTask.testDynamicFilters(TestHttpRemoteTask.java:265)
2021-01-14T19:36:20.5734924Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-14T19:36:20.5744641Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-14T19:36:20.5755112Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-14T19:36:20.5761458Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-14T19:36:20.5769620Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-14T19:36:20.5777894Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2021-01-14T19:36:20.5785690Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2021-01-14T19:36:20.5793601Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-01-14T19:36:20.5800456Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-01-14T19:36:20.5808795Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-14T19:36:20.5817469Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-14T19:36:20.5823171Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
@phd3 shall we reopen https://github.com/trinodb/trino/issues/5809 ?

**Comment by phd3** [comment]
@findepi yeah, I just re-opened it for now. We can mark the test as flaky (and prioritize investigating it) if we see more.

**Pull request merged**
