### PR TITLE
Add support for Elasticsearch query string syntax

### PR DESCRIPTION
**Pull request by martint**
The connector now supports queries of the form:

    SELECT * FROM "t: <elasticsearch query string>"

The language is described here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

### CODE REVIEW

**Comment by dain** [comment]
This should have some docs also.

**Comment by MT2017081** [comment]
GET /twitter/doc/_search
{
  "query": {
    "match": {
      "message": "saw jungle"
    }
  }
}

Hi, I am using presto version-316 and elasticsearch version-6.1.0, I want to make an sql query from presto which is equivalent to the above full-text-query.
So, what query should i write to get the result ?

**Comment by MT2017081** [comment]
Hi, what could be the equivalent presto query for the below elasticsearch query?
GET /_search?q=name:xyz

**Comment by sivatarunp** [comment]
The following query `SELECT * from "companydatabase2: YOYO"`; is being converted to  below Elasticsearch query
```
query: {"size":1000,"query":{"bool":{"must":[{"query_string":{"query":" yoyo","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":["Address","Age","Designation","FirstName","Gender","Interests","LastName","MaritalStatus","Salary"],"excludes":[]}}
```
If you observe its lowercasing the string we are searching, which is not expected leading to wrong results. Why is it happening and is there a way to avoid it?

**Comment by hashhar** [comment]
use the https://trino.io/docs/current/connector/elasticsearch.html#raw-query-varchar-table function instead of this old way.

**Comment by sivatarunp** [comment]
But I need to extend my query to use trino related functions something like this,
```
SELECT
  regexp_extract(designation,'Manager') as role FROM(
SELECT *
FROM
  TABLE(
    example.system.raw_query(
      schema => 'default',
      index => 'companydatabase2',
      query => '{
        "query": {
          "query_string": {
            "query": "YOYO"
          }
        }
      }'
    )
  )
);
```
which is failing throwing error unknown field designation.Here designation is supposed to be field in companydatabase2 index. How to achieve this

**Comment by hashhar** [comment]
> Here designation is supposed to be field in companydatabase2 index.

Instead of assuming you can check what data is actually returned by running:

```
SELECT *
FROM
  TABLE(
    example.system.raw_query(
      schema => 'default',
      index => 'companydatabase2',
      query => '{
        "query": {
          "query_string": {
            "query": "YOYO"
          }
        }
      }'
    )
  )
);
```

You'll notice it's JSON so you'll need to do a `json_query` or other json function to get to the `designation` field.

It's mentioned in the docs that the result of `raw_query` is the JSON response from Elasticsearch as it is.

**Comment by sivatarunp** [comment]
Yes I have already tried it, and checked that we have to use various json_parse functions to get the required result, which actually seems very intensive. Can we know what is the reason for deprecating the old way and the reason for actually converting the query/table_name  to lower case ?

**Comment by hashhar** [comment]
reason for deprecating: the issues you are running into.

reason for lowercasing: https://github.com/trinodb/trino/issues/17

**Comment by sivatarunp** [comment]
Thanks @hashhar . One more question I have is why is trino ES raw json as response? We already have functions to get the row form of data which are being  used for pushdown. For ex: where clause on integer field, will be pushed to ES and its converted to row form. Is it possible to use the same here instead of using extra json functions on this data ?

**Comment by sivatarunp** [comment]
Ex: `SELECT LastName from "companydatabase2" where Age=25;` This SQL query is entirely pushed down to ES, and trino fires below ES query 
```
{"size":1000,"query":{"bool":{"filter":[{"term":{"Age":{"value":25,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":["LastName"],"excludes":[]},"sort":[{"_doc":{"order":"asc"}}]}
```
The result of this is simple LastName row

Now firing the same query, using raw query gives result in form ES response, instead of LastName row alone. Is it possible to reuse the same logic which trino is using to confine the response coming from ES in case1, to be done in case2 also? Any specific way of querying to achieve that/config to achieve that?

**Comment by hashhar** [comment]
Please file a separate issue about that.

It's not trivial to do and additionally against the purpose of why `raw_query` exists. If possible it would make sense to expose it via a separate table function.

**Pull request merged**
