### PR TITLE
Make randomTableSuffix utility method public

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by martint** [comment]
What’s the motivation? You might also want to add a comment describing why it needs to be that way, otherwise someone will “clean it up” and undo the change in the future.

**Comment by electrum** [comment]
This is a library used for testing. Obviously, it's public so that other test code can call it. I don't think we need to annotate all of the public methods in a library with a comment like
```java
// this method is part of the public API
```
Perhaps I should I ask the question, what stops someone from "cleaning up", e.g., breaking any other public API?

**Comment by martint** [comment]
Clearly it's not a public API, since it's a private method. My concern is that if there are no usages whatsoever in the code that rely on it being public, someone might inadvertently make it private again.

**Comment by electrum** [comment]
This is part of the public API by virtue of being public. Since this doesn’t seem to be sufficient for you, what, specifically, would you like to see here?

**Pull request merged**
