### PR TITLE
Make EncoderUtil public

### PR DESCRIPTION
**Pull request by kokosing**
Make EncoderUtil public

### CODE REVIEW

**Comment by martint** [comment]
What's the motivation? This is supposed to be an implementation detail of the Map and Row encoders, not a public API for connectors to use.

**Comment by kokosing** [comment]
> What's the motivation?

Encoding null positions as bit set seems to be very generic algorithm. I understand your concern that is not the part of SPI, on the other hand it is useful utility that I would prefer reuse instead of copying.

**Comment by dain** [comment]
> > What's the motivation?
> 
> Encoding null positions as bit set seems to be very generic algorithm. I understand your concern that is not the part of SPI, on the other hand it is useful utility that I would prefer reuse instead of copying.

In my experience new types with new block encodings are exceedingly rare, so copying doesn't seem like a big burden.  If you feel strongly, about having a utility for this, then I would add it to the plugin toolkit.

**Comment by kokosing** [comment]
> If you feel strongly

I don't. Closing.

**Comment by kokosing** [comment]
Thanks for feedback!

**Pull request closed without merging**
