### PR TITLE
Fix flaky TestConnectorEventListner

### PR DESCRIPTION
**Pull request by s2lomon**

### CODE REVIEW

**Comment by kokosing** [comment]
What was the issue? Have you were able to reproduce flakiness locally?

**Comment by s2lomon** [comment]
@kokosing yes. The issue was that I was expecting 2 events only, instead of 3 (create, finish, split) and it seems that from time to time these events were handled in a different order hence, later assertions were failing. I would like to rewrite it to awaiting for successful assertion resolution, but I don't have any lose cycles atm. especially that it would require cleanup other tests using these assertions in the name of not introducing another assertions for these events.

**Comment by kokosing** [comment]
It would be nice to capture such information in commit message.

**Comment by kokosing** [comment]
Merged as https://github.com/prestosql/presto/commit/af42e81b6ad25fab0002ee700caeb6bff903a63e.

Thanks!

**Pull request closed without merging**
