### PR TITLE
Fix ORC Bloom Filter #921

### PR DESCRIPTION
**Pull request by dilipkasana**
Fix for #921 , changing key from `StreamId` to `Integer`

### CODE REVIEW

**Comment by dain** [comment]
This is commit is virtually the same as the first commit in #914.  If you can sign the CLA (https://github.com/prestosql/cla), I'll push this one and then rebase #914 on that.

**Comment by dilipkasana** [comment]
> This is commit is virtually the same as the first commit in #914. If you can sign the CLA (https://github.com/prestosql/cla), I'll push this one and then rebase #914 on that.

@dain I have sent the CLA signed.Please push the commit.

**Comment by martint** [comment]
@cla-bot check

**Comment by martint** [comment]
@cla-bot check

**Pull request merged**
