### PR TITLE
Show distributed plan by default in EXPLAIN

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by findepi** [comment]
in general, I prefer reading non-DISTRIBUTED plans.

**Comment by martint** [comment]
I prefer the distributed plan, actually. It has less nesting, it's shows the distribution type of each fragment (vs having to infer by the presence of different kinds if exchanges), shows the partitioning scheme of the output of a fragment, etc. I've been meaning to make this change myself for a while.

**Comment by electrum** [comment]
@findepi I think you are in the minority. I never look at the logical plan except by accident.

**Comment by findepi** [comment]
> it's shows the distribution type of each fragment

Maybe i am being too simplistic to look into this often.

The thing i don't like about distributed plan is that i need to follow numerical references between stages.

**Pull request merged**
