### PR TITLE
Rename VarcharsTest to match Surefire naming pattern

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by electrum** [comment]
Thanks, fixed

**Comment by findepi** [comment]
@electrum there are quite a few classes named `XxxTest` (especially in product tests world). You may want to update them too.

**Comment by electrum** [comment]
@findepi The only instances I could find were product tests. The root POM changes the Surefire configuration to only check for `Test*`, but I don't know if that also applies to product tests. If it does, that means those classes aren't being run today (which is the case for `VarcharsTest`).

**Comment by findepi** [comment]
We could
- register `Test*` and `*Test` in surefire
- have a check at runtime (should be easy with a testng listener loaded via service loader) that enforces test naming convention

This way, we would close the loop and make it highly unlikely to have tests which are not run.

**Pull request merged**
