### PR TITLE
Remove check that each node has cached data

### PR DESCRIPTION
**Pull request by sopel39**
Presto uses variable names when creating
data files. Therefore it might happen that
every data file will be cached on same node
since files are distributed based on file name
hash.

### CODE REVIEW

**Comment by findepi** [comment]
How many different data files (names) do we use in the test?
(and what's the hash function?)

**Comment by sopel39** [comment]
> How many different data files (names) do we use in the test?
(and what's the hash function?)

5 splits = 5 files. File name is non-deterministic in test. But for testing scheduling locality we don't really need cache to be distributed. We just need that splits are scheduled on nodes/node with data.

**Comment by losipiuk** [comment]
It was actually nice assertion. Can we bump number of files to 50 and leave the assertion?

**Comment by sopel39** [comment]
> It was actually nice assertion. Can we bump number of files to 50 and leave the assertion?

It increases test time (even 10 make is 1:40s vs 40s) and there will be misassigned splits then (and non-local reads)

**Comment by losipiuk** [comment]
> > It was actually nice assertion. Can we bump number of files to 50 and leave the assertion?
> 
> It increases test time (even 10 make is 1:40s vs 40s) and there will be misassigned splits then (and non-local reads)

Ok - lets have it then. It just open place for false positives (e.g. test misconfiguration so we are actually running everything on single node).

**Pull request merged**
