### PR TITLE
Remove JdbcConnectorId from base-jdbc connector

### PR DESCRIPTION
**Pull request by kokosing**
Remove JdbcConnectorId from base-jdbc connector

### CODE REVIEW

**Comment by dain** [comment]
@cla-bot check

**Comment by electrum** [comment]
Typo "Introdocue" in commit message

**Comment by electrum** [comment]
I disagree with adding `CatalogName` to the SPI, as it's only being used as utility class, rather than as an interface between the engine and plugins. Also, the lowercase semantics are problematic as we move to properly support SQL identifiers.

Let's add a `JdbcCatalogName` instead. Otherwise, this PR looks good. Thanks for continuing the connector ID cleanup.

**Comment by findepi** [comment]
"Remove connectorId from JDBC connector handles"

Skimmed. This one looks good. Why `io.prestosql.plugin.jdbc.BaseJdbcClient#connectorId` remains needed?

**Comment by kokosing** [comment]
Reverted `CatalogName` and remove `JdbcConnectorId` entirely.

**Pull request merged**
