### PR TITLE
Update to Airlift 0.195

### PR DESCRIPTION
**Pull request by electrum**
Fixes https://github.com/prestosql/presto/issues/2981

### CODE REVIEW

**Comment by martint** [comment]
Can you add a note to the commit message indicating how it affects Presto? Also, maybe link to the issues it fixes, such as the t-digest index out of bounds bug.

**Comment by electrum** [comment]
Updated description and added link.

**Comment by tooptoop4** [comment]
can this get in 332 release?

**Comment by electrum** [comment]
@tooptoop4 yes, it will be in 332

**Pull request merged**
