### PR TITLE
Upgrade Guava to 28.2-jre version

### PR DESCRIPTION
**Pull request by medb**

### CODE REVIEW

**Comment by electrum** [comment]
Please update this in https://github.com/airlift/airbase

**Comment by electrum** [comment]
Looks like 29.0 is the latest version, so we should use that.

**Comment by medb** [comment]
Seems like Airbase already updated to Guava 29: https://github.com/airlift/airbase/commit/88e4e3ae3454d137549cce960793cc56af80cb7d

If it means that latest versions of Presto use Guava 29 dependency, feel free to close this PR.

**Comment by kokosing** [comment]
Yes we are using 29.0-jre:
image

Thanks. Closing.

**Pull request closed without merging**
