### PR TITLE
add worklist web ui

### PR DESCRIPTION
**Pull request by zm12397**
This commit add list of workers' infomation in the web UI.
This implementation add an GET http interface that is list the workers.
I hava  included the React-generated JavaScript.
The visualized cluster worker list is necessary for monitoring and operation and maintenance,so I thought we should add this page.

The effect is as follows:
1.The web UI index add a link for workers
web_ui_index
2.Click the Active Workers region,then open the workers page
web_ui_list
This page shows the worker list,contains NodeID and NodeIP per worker node;
3.Click one worker item,then open the worker's details
web_ui_worker

### CODE REVIEW

**Comment by electrum** [comment]
@cla-bot check

**Comment by electrum** [comment]
Thanks for submitting this. Having a worker list in the UI seems useful. I'll let @raghavsethi do a full review and comment on the UI design.

From a REST perspective, rather than having a separate `workerList` resource, we should put the list at `/v1/worker` (in the existing `WorkerResource`). This makes it hierarchical, so that `/v1/worker` is the list and things like `/v1/worker/$nodeId/status` is are for the specific worker. This is similar to other resources like `/v1/query`.

Also, I would get rid of the `ID` column on the list, since it seems to be made up only for this page (unlike stage or task IDs in a query which actually exist in the query engine).

**Comment by zm12397** [comment]
> Thanks for submitting this. Having a worker list in the UI seems useful. I'll let @raghavsethi do a full review and comment on the UI design.
> 
> From a REST perspective, rather than having a separate `workerList` resource, we should put the list at `/v1/worker` (in the existing `WorkerResource`). This makes it hierarchical, so that `/v1/worker` is the list and things like `/v1/worker/$nodeId/status` are for the specific worker. This is similar to other resources like `/v1/query`.
> 
> Also, I would get rid of the `ID` column on the list, since it seems to be made up only for this page (unlike stage or task IDs in a query which actually exist in the query engine).

Thanks for your advice.
I have changed the REST and remove the ID column on the list.

**Comment by zm12397** [comment]
Thanks for your advice.
I have changed the REST and remove the ID column on the list.


But the code check seems to have some problems.

The details showing the WEBUI ENV has failed and I don't know the reason,can you help me?I will be very grateful.




The url: https://github.com/prestosql/presto/pull/126

The error screenshot: 

Thanks agin.




Yours faithfully,
zm12397.



-----原始邮件-----
发件人:"David Phillips" <notifications@github.com>
发送时间:2019-02-03 13:47:44 (星期日)
收件人: prestosql/presto <presto@noreply.github.com>
抄送: xiaoMing <zm12397@zju.edu.cn>, Author <author@noreply.github.com>
主题: Re: [prestosql/presto] add worklist web ui (#126)



Thanks for submitting this. Having a worker list in the UI seems useful. I'll let @raghavsethi do a full review and comment on the UI design.

From a REST perspective, rather than having a separate workerList resource, we should put the list at /v1/worker (in the existing WorkerResource). This makes it hierarchical, so that /v1/worker is the list and things like /v1/worker/$nodeId/status is are for the specific worker. This is similar to other resources like /v1/query.

Also, I would get rid of the ID column on the list, since it seems to be made up only for this page (unlike stage or task IDs in a query which actually exist in the query engine).

**Comment by raghavsethi** [comment]
Here are the primary things we need to resolve:
1. There is code copied from other parts of the codebase that doesn't make sense in this context. For example, addToHistory is used to collect data for sparklines, but there are no sparklines on this page.
2. The worker list page looks very bare and does not have information that a user would expect to see. For example, coordinators, dispatcher, and worker roles should be listed. I would also like to see something useful like uptime, GC, CPU etc. This can be done client side (so that the coordinator does not need to keep this information) and async (but will need a proxy layer in the coordinator, similar to ThreadResource).
3. This is the only large header on the main page that is a link, which makes it look out of place and confusing. We will have to figure out where to put the entry point to this page. Perhaps the main title can have a worker view. But before we do that we definitely need to make sure the page is useful and well designed.

**Comment by martint** [comment]
Closing for now. Please re-open once you've addressed the comments above.

**Pull request closed without merging**
