### PR TITLE
Fix lag while printing CLI output

### PR DESCRIPTION
**Pull request by ryanrupp**
Due to Queues.drain waiting up to 3 seconds for the minimum of 1000 elements to be available which wouldn't happen for smaller output. Use a special end token object to indicate the end of the result reading so the printing thread can unblock from poll.

### CODE REVIEW

**Comment by ryanrupp** [comment]
Fixes the second noted gap in https://github.com/prestosql/presto/issues/2008 although I'm not sure what the brief < 1s gap on initial submission is still. Doesn't appear to be related to the output printing though which was changed recently in https://github.com/prestosql/presto/pull/965

**Comment by ryanrupp** [comment]
Hrm, looks like this is getting failures like it starts to execute the next command before the previous one hasn't completed e.g. below is complaining schema isn't set but it's set in the previous step:
```
2019-11-16 02:41:41 INFO: FAILURE     /    io.prestosql.tests.cli.TestPrestoCli.shouldHandleTransaction (Groups: cli) took 3.3 seconds
2019-11-16 02:41:41 SEVERE: Failure cause:
java.lang.AssertionError: 
Expecting:
 <["Query 20191115_205641_00880_7ym7k failed: line 1:1: Schema must be specified when session schema is not set",
    "LINE 1: create table txn_test (x bigint)",
```

at  `at io.prestosql.tests.cli.TestPrestoCli.shouldHandleTransaction(TestPrestoCli.java:252)`

Not immediately seeing how that would happen, will follow up on this.

**Comment by ryanrupp** [comment]
Think I fixed the above now, was trying to use `Futures.getDone` for readability but there's certain paths/short race condition before where the future isn't actually done but the end token has been published to the queue.

**Comment by ryanrupp** [comment]
I built Travis again and it passed although the previous build did fail due to the CLI getting an empty response somehow (not sure if this is a known intermittent failure although it is suspiciously related to the changes here so it's possible I introduced this somehow). I'm trying to link the old build for reference but I'm not that familiar with the Travis UI on how to recall a previous build, cc @electrum

**Comment by electrum** [comment]
I found the old build here: https://travis-ci.com/prestosql/presto/builds/136747029

The code looks correct to me. I'll merge this now and we'll keep an eye on the CI to see if there are any intermittent failures that indicate a race condition or other bug. Thanks for fixing this!

**Pull request merged**
