### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
Failure is interesting:

```
2020-04-06T10:42:23.7178521Z [ERROR] Tests run: 1924, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,250.296 s <<< FAILURE! - in TestSuite
2020-04-06T10:42:23.7187568Z [ERROR] testRunningQuery(io.prestosql.execution.resourcegroups.db.TestQueuesDb)  Time elapsed: 1.098 s  <<< FAILURE!
2020-04-06T10:42:23.7191920Z java.lang.IllegalArgumentException: value is negative
2020-04-06T10:42:23.7196865Z 	at io.airlift.units.Preconditions.checkArgument(Preconditions.java:26)
2020-04-06T10:42:23.7201482Z 	at io.airlift.units.Duration.<init>(Duration.java:69)
2020-04-06T10:42:23.7206756Z 	at io.airlift.units.Duration.succinctDuration(Duration.java:59)
2020-04-06T10:42:23.7214805Z 	at io.prestosql.execution.resourcegroups.InternalResourceGroup.getFullInfo(InternalResourceGroup.java:167)
2020-04-06T10:42:23.7218587Z 	at java.util.Optional.map(Optional.java:215)
2020-04-06T10:42:23.7229605Z 	at io.prestosql.execution.resourcegroups.InternalResourceGroupManager.tryGetResourceGroupInfo(InternalResourceGroupManager.java:99)
2020-04-06T10:42:23.7236591Z 	at io.prestosql.execution.resourcegroups.db.TestQueuesDb.testRunningQuery(TestQueuesDb.java:100)
2020-04-06T10:42:23.7241121Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-04-06T10:42:23.7247258Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-04-06T10:42:23.7252961Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-04-06T10:42:23.7256752Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-04-06T10:42:23.7263083Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-04-06T10:42:23.7268225Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-04-06T10:42:23.7273170Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-04-06T10:42:23.7278344Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-04-06T10:42:23.7284400Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-06T10:42:23.7292283Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-04-06T10:42:23.7299272Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-04-06T10:42:23.7303596Z 	at java.lang.Thread.run(Thread.java:748)
2020-04-06T10:42:23.7304816Z 
```

**Comment by findepi** [comment]
There already is #3333

**Comment by wendigo** [comment]
@findepi I’m updating testcontainers among other things

**Comment by findepi** [comment]
@wendigo i am not saying your PR is redundant.

**Comment by wendigo** [comment]
@findepi I'll rebase on top of #3333 to drop commits if necessary.

**Comment by electrum** [comment]
I merged #3333, so please rebase.

**Comment by wendigo** [comment]
@electrum rebased

**Comment by wendigo** [comment]
ping @electrum

**Pull request merged**
