### PR TITLE
Fix display error of datetime function document

### LINKED ISSUE #3079: current_date in docs is shown with braces
https://prestosql.io/docs/current/functions/datetime.html#current_date:

> current_date()
>   Returns the current date as of the start of the query.

but in SQL this must be used without braces:

```
presto> SELECT current_date;
   _col0
------------
 2020-03-12

presto> SELECT current_date();
Query 20200312_100603_00004_kvt2r failed: line 1:20: mismatched input '('. Expecting: '%', '*', '+', ',', '-', '.', '/', 'AND', 'AS', 'AT', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', 'WHERE', '[', '||', <EOF>, <identifier>, <predicate>
```

Same applies to other `current_*` functions.

### PR DESCRIPTION
**Pull request by amosannn**
Fixes #3079

### CODE REVIEW

**Comment by amosannn** [comment]
@cla-bot check

**Comment by amosannn** [comment]
@cla-bot cla mail has been sent

**Comment by amosannn** [comment]
@cla-bot check

**Comment by amosannn** [comment]
> Thanks for your contribution. Could you fix `current_user` as well? (Please capitalize the commit message: e.g. Fix display...)
> https://prestosql.io/docs/current/functions/session.html#current_user

@ebyhr Hi, the `current_user` was fixed, but i don't know why the cla-bot still has this response after sending the CLA email ?_?

**Comment by findepi** [comment]
cc @electrum

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
@amosannn Sorry for bothering you. You were added on March 20.

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
