### PR TITLE
Updated jQuery to version 3.5.1

### PR DESCRIPTION
**Pull request by ShashwatArghode**
- Updated jQuery to 3.5.1 to fix Presto Web UIs known security vulnerabilities (https://jquery.com/download/))
- Updated bootstrap to version 3.4.1 which is compatible with jQuery > 3.0 (https://getbootstrap.com/docs/3.4/customize/)

Resolves: #3534

### CODE REVIEW

**Comment by raghavsethi** [comment]
@ShashwatArghode Have you clicked through all the various parts of the UI and confirmed that they are all functional and look similar?

**Comment by ShashwatArghode** [comment]
> @ShashwatArghode Have you clicked through all the various parts of the UI and confirmed that they are all functional and look similar?

@raghavsethi I have checked all parts of the UI, they are functional and similar. Also, no error/exception on inspection of the different parts of the UI in chrome.

**Comment by ShashwatArghode** [comment]
> Great, looks good! Thanks for your contribution! (I'm assuming test failures are unrelated).
> 
> Could you rebase and force push again to kick the test runner?

Thank you @raghavsethi. The test failure was unrelated and all tests are passing after rebase.

**Comment by martint** [comment]
Merged as b33c4ffd9745af6d15e909e95d2be8a729cc5db1. Thanks!

**Pull request closed without merging**
