### PR TITLE
Use Cache instead of LoadingCache

### PR DESCRIPTION
**Pull request by zaz968m**
Loader in cache.get(key, loader) is able to refer
to state other than that in the key.
This is a preparation step for enhancing some loaders
with necessary runtime information (e.g. query id)
which cannot be stored within cache key.

### CODE REVIEW

**Review by kokosing — APPROVED** [review]

**Comment by zaz968m** [comment]
Failing check is a flaky one https://github.com/prestosql/presto/issues/4568

**Comment by findepi** [comment]
> Loader in cache.get(key, loader) is able to refer to state other than that in the key.


that's usually a downside. loading cache API ensures that cache content is derived from cache key, which is generally very desireable and doing otherwise is (as i have witnessed) error prone

i understand why we're doing this in this class, but worth amending the commit messgae with more tailored explanation

**Comment by zaz968m** [comment]
@findepi please AC

**Review by findepi — APPROVED** [review]

**Comment by kokosing** [comment]
Merged, thanks!

**Pull request merged**
