### PR TITLE
Right and outer join should produce unordered global streams

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Comment by sopel39** [comment]
Extracted from: https://github.com/prestosql/presto/pull/315

**Comment by findepi** [comment]
LGTM. 
@sopel39 please change commit message to reflect you're fixing a bug. Eg
```
Fix RIGHT/OUTER Join stream ordering property derivations
```

**Comment by martint** [comment]
Is there a test case that reproduces whatever issue this fixes?

**Comment by sopel39** [comment]
@martint I think it's quite difficult to produce.
build side would need to be single stream (to be sorted) with sort operator directly below join (and above exchange), so this implies broadcast join and probe side also being single stream.
I don't think such plan is possible today, but it could possible be produced.
However, the code here is broken and needs to be fixed

**Pull request merged**
