### PR TITLE
Remove extra maven MAVEN_OPTS

### PR DESCRIPTION
**Pull request by kokosing**
Remove extra maven MAVEN_OPTS

This option looks obsolete. Also it looks overwritten with
.mvn/jvm.config.

### CODE REVIEW

**Comment by electrum** [comment]
`MAVEN_OPTS` takes precedence. You can verify this by doing `MAVEN_OPTS="-Xmx1M" mvn ...` and seeing it crash. We can't have an 8GB limit on Travis since it doesn't have that much memory. But I can see value in removing `MAVEN_OPTS` and lowering the limit in `jvm.config`.

**Comment by electrum** [comment]
However, a concern with doing this is that local builds might need more memory than Travis, due to having more parallel builds, etc. Or there might be build activities run locally that aren't run on Travis. We can try it out if you want.

**Comment by kokosing** [comment]
>  We can't have an 8GB limit on Travis since it doesn't have that much memory.

Notice that travis build has passed. So actually we have that amount, or we haven't reached that point.

**Comment by electrum** [comment]
It's expected that the build would pass, since it works today with `512M`. But I don't think it's good practice to set the heap larger than the available memory.

Travis says the machines have 7.5GB: https://docs.travis-ci.com/user/reference/overview/

**Comment by findepi** [comment]
Also, the more memory we give to maven, the less we have for the tests.

**Comment by kokosing** [comment]
Thanks guys. Now I understand how it works.

**Pull request closed without merging**
