### PR TITLE
Missing message in assertInvalidExtract

### LINKED ISSUE #5586: Missing message in assertInvalidExtract
``` java
private static void assertInvalidExtract(String inputJson, String jsonPath, String message)
{
    assertPrestoExceptionThrownBy(() -> doJsonExtract(inputJson, jsonPath))
            .hasErrorCode(INVALID_FUNCTION_ARGUMENT);
}
```

should be 

``` java
private static void assertInvalidExtract(String inputJson, String jsonPath, String message)
{
    assertPrestoExceptionThrownBy(() -> doJsonExtract(inputJson, jsonPath))
            .hasErrorCode(INVALID_FUNCTION_ARGUMENT)
            .hasMessage(message);
}
```

Message is missing.

### PR DESCRIPTION
**Pull request by brandboat**
Fixes #5586

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Thanks for fixing this! Please submit CLA and remove  following `.` from commit message. 
https://github.com/prestosql/presto/blob/master/DEVELOPMENT.md#format-git-commit-messages is the commit guideline we follow.

**Comment by martint** [comment]
@cla-bot check

**Comment by brandboat** [comment]
Gentle ping @ebyhr. Removing `.` from commit completed.

**Comment by martint** [comment]
Merged, thanks for your contribution!

**Pull request merged**
