### PR TITLE
Revert "Update JLine to 3.17.1"

### PR DESCRIPTION
**Pull request by wendigo**
This reverts commit 299f6d90835d508f4b7dabf3c26c7e1c3e911db3.

### CODE REVIEW

**Review by electrum — APPROVED** [review]

**Comment by martint** [comment]
Add a comment in the commit message explaining why

**Comment by wendigo** [comment]
@martint comment added

**Comment by findepi** [comment]
is there a jline issue that we could link to in the pom.xm to prevent upgrading too quickly the next time?

**Comment by wendigo** [comment]
@findepi I think that we are using JLine wrong but I'm not an expert here.

**Comment by wendigo** [comment]
@findepi problem is that `TerminalBuilder.builder().build().width()` returns 0 since 3.14.0. I'd expect JLine to detect number of columns/rows properly but maybe we are doing something wrong on our side.

**Comment by wendigo** [comment]
Superseded by https://github.com/prestosql/presto/pull/6119

**Pull request closed without merging**
