### PR TITLE
Support Confluent schema registry

### LINKED ISSUE #2105: Support Confluent Schema Registry
[Confluent Schema Registry](https://github.com/confluentinc/schema-registry) is commonly used to store Avro schemas, and reduce Kafka records size by storing an ID instead of the schema on the record message.

Currently, only Avro files are supported to decode Kafka records.

I'd like to propose adding support for Schema Registry on the Avro decoder.

### PR DESCRIPTION
**Pull request by jeqo**
Fix #2105

This PR is initially meant to contribute to the discussion, and if useful could be a baseline to implement this feature.

### CODE REVIEW

**Comment by martint** [comment]
@cla-bot check

**Comment by kokosing** [comment]
@jeqo are you still willing to work on this. There is also https://github.com/prestosql/presto/pull/2361 that is  going to address similar use case. What do you think about the other approach?

**Comment by elonazoulay** [comment]
Split into 2 pull requests. The schema registry pull request is #2499 elonazoulay:cf-schema-registry

**Comment by elonazoulay** [comment]
I split #2361 into 2 pull requests. The schema registry pull request is now #2499.

**Comment by jeqo** [comment]
Closing in favor of #2499

**Pull request closed without merging**
