### PR TITLE
Push down additional aggregation functions for SQL Server

### PR DESCRIPTION
**Pull request by charlesjmorgan**
Push down `stddev, stddev_samp, stddev_pop, variance, var_samp, var_pop` aggregate functions for SQL server

### CODE REVIEW

**Comment by mosabua** [comment]
Please add update of the docs to this PR

**Comment by alexjo2144** [comment]
Looks good to me, just kick off a fresh build for the flaky test failure.

**Comment by findepi** [comment]
Merged as 5622e4853c1e95991ed978d5d304c19c01b2a24d, thanks!

**Comment by findepi** [comment]
> Please add update of the docs to this PR

I am not entirely convinced it is actually useful to mention which aggregate functions are pushed down. -- for this to be sufficient for users, they would need to know their exact signsatures (not just names), and the coercion rules, etc. I think we could as well remove the funciton listing from docs and just say that there is "best effort agg pushdown"
@mosabua wdyt?

**Comment by mosabua** [comment]
Well. users have asked on slack and customers also have asked for which functions this works. And the generic docs shows how to troubleshoot and see if it does or does not work. I think we should maintain the list for users

**Comment by findepi** [comment]
Again, it is much much more subtle than a bunch of function names.

**Comment by mosabua** [comment]
Sure... we can and should add more information about these subtleties over time as well. But this is much better than just a generic message.

**Pull request closed without merging**
