### PR TITLE
Allow multiple or missing Hive bucket files

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by martint** [comment]
Can you mention the motivation for this in the commit message (Compatibility with version X of Hive or whatever else it helps with)?

**Comment by findepi** [comment]
@electrum do you happen to know if this os functionality similar to https://github.com/prestodb/presto/pull/6282?

**Comment by electrum** [comment]
@findepi It is similar but more flexible, as this allows any number of files per bucket, whereas that one seems to require the file count to be a multiple of the bucket count. This also changes Presto to write files using the Hive naming convention.

**Comment by jiegzhan** [comment]
With EMR 5-21 (Presto 0.215), still got this issue: Query 20191107_222140_00006_rf89j failed: Hive table 'dev.wifi_logs' is corrupt. The number of files in the directory (256) does not match the declared bucket count (64) for partition: date_key=2019-11-05

Are there any configurations to ignore this check?

**Comment by findepi** [comment]
@jiegzhan 
in 0.215 the check is unconditional, cannot be disabled. That version simply does not handle the case you're in.
Please try it out in Presto 324 https://prestosql.io/download.html . this will just work now. 

If you can't upgrade just yet for some reason, please ask for more advice on `#troubleshooting` channel on our slack (https://prestosql.io/slack.html).
See you there!

**Comment by akhilnaidu** [comment]
> With EMR 5-21 (Presto 0.215), still got this issue: Query 20191107_222140_00006_rf89j failed: Hive table 'dev.wifi_logs' is corrupt. The number of files in the directory (256) does not match the declared bucket count (64) for partition: date_key=2019-11-05
> 
> Are there any configurations to ignore this check?

You are referring to the Prestodb distribution (release 0.215) that comes along with EMR while this feature is a part of Prestosql release 312.
Currently this is not supported in EMR Prestodb distribution.

**Pull request merged**
