### PR TITLE
Fix sequence encodings in Checkpoints.getStreamCheckpoints

### PR DESCRIPTION
**Pull request by kokosing**
Fix sequence encodings in Checkpoints.getStreamCheckpoints

DWRF sequence encoding was introduced in
87f7e51c99963787f71027e749cf1e10815180fb to support read DWRF flat map.

However, Checkpoints.getStreamCheckpoints still uses the column level
encoding, even for flat map.

This causes failure when reading from a DWRF flat map where
the DWRF sequence use different encodings for different keys.
(for example, some key uses dictionary encoding while some other
keys use direct encoding)

Extracted from:
https://github.com/prestodb/presto/commit/eb011ec82f6de28a49c8e95cf53c7a01508d0293

### CODE REVIEW

**Comment by dain** [comment]
We can merge this, but since there is no spec or alternate implementation for DWRF, we have no way to verify the correctness of the change.

**Comment by kokosing** [comment]
@dain Would you like add release notes for this?

**Comment by dain** [comment]
I added the release notes

**Comment by kokosing** [comment]
Thanks!

**Pull request merged**
