### PR TITLE
Improve tests for reserved word identifiers

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by electrum** [comment]
The parser tests verify that the expected tree round trips.

**Comment by martint** [comment]
But not explicitly, so it's not obvious. We will also want to test that starting from a AST structure, the formatter produces a certain output without having to involve the parser.

**Comment by electrum** [comment]
I agree, it’s not obvious. Except to me, as I’m the one who added that to get full coverage of the formatter, without having to write all the tests twice.

Before that, not everything worked, and people would add syntax parsing without formatting. That shouldn’t be possible now if you add parser tests. (unless you make corresponding mistakes in both the formatter and the tree node equality)

Maybe we should document this at the top of the test class?

**Comment by martint** [comment]
> Maybe we should document this at the top of the test class?

That would certainly help

**Pull request merged**
