### PR TITLE
fix view select privilege check bug

### PR DESCRIPTION
**Pull request by chenxyz707**
there is something wrong for checking view select privilege

### CODE REVIEW

**Comment by ebyhr** [comment]
Thanks for creating this PR, but it's intentional. Please see https://github.com/prestosql/presto/pull/1833

**Comment by ebyhr** [comment]
I would invite you to join the community Slack If you haven't yet joined there. 
https://prestosql.io/slack.html

**Comment by electrum** [comment]
This is intentional and matches the SQL standard for view security. In SQL, views are special in that they execute with permissions of the owner. This means that the owner of the view is effectively granting permissions to the user running the query, and thus must have the equivalent of the SQL standard `GRANT ... WITH GRANT OPTION`.

**Comment by electrum** [comment]
From the [Teradata CREATE VIEW](https://docs.teradata.com/reader/eWpPpcMoLGQcZEoyt5AjEg/ZbtDi0PRpAjXdTITDqMxqw) documentation:

> If a user other than the owner accesses a view, then all of the relevant privileges needed by the immediate owner of the view to access underlying tables and views must also be held by the immediate owner of the view WITH GRANT OPTION.

Oracle has the same behavior, explained in this [blog](http://www.petefinnigan.com/weblog/archives/00001442.htm) or this [Stackoverflow question](https://stackoverflow.com/questions/36860494/bypass-table-privilege-and-with-grant-option-by-creating-views).

**Comment by electrum** [comment]
I’m closing the PR since the current behavior is intended. Thank you for your contribution. We’re happy to discuss this further here or Slack.

**Comment by dain** [comment]
Alternatively, you can create the view with `SECURITY INVOKER`, which will cause the view to execute with the permissions of the user executing the query instead of the permission of the view owner.  See https://prestosql.io/docs/current/sql/create-view.html#security for more information.

**Pull request closed without merging**
