### PR TITLE
Remove unused JOL references from JDBC driver

### PR DESCRIPTION
**Pull request by ajorg-aws**
Per #1461 JOL is no longer included in the JDBC driver, so the license
text can be removed to avoid confusion.

Closes: #1461

### CODE REVIEW

**Comment by electrum** [comment]
Thanks! Can you also remove the shade relocation rule from the POM?

**Comment by ajorg-aws** [comment]
> Can you also remove the shade relocation rule from the POM?

Happy to do so. I wasn't sure if it should be left in case JOL returns to the JDBC driver at a later date.

**Comment by electrum** [comment]
Thanks for updating. Can you squash the commits and remove the commit descriptions? We can simplify the title so that the description isn't necessary:

> Remove unused JOL references from JDBC driver

We usually only put *Closes*, *Fixes*, in the PR description, since having them in the repository isn't helpful when looking at commit messages. (ideally, messages should be self descriptive without needing to reference an external issue)

**Comment by ajorg-aws** [comment]
Of course. Thanks for your patience in teaching me your preferences here.

**Comment by ajorg-aws** [comment]
Anything else I needed to do here? No pressure from me, just don't want to drop the ball.

**Comment by electrum** [comment]
Thanks for the reminder. Merged!

**Comment by ajorg-aws** [comment]
Thanks!

**Pull request merged**
