### PR TITLE
Remove angle brackets support in type signature parsing

### PR DESCRIPTION
**Pull request by willshen**
Remove angle brackets support now that ROW<TYPE>(name) legacy row type signature is no longer supported (removed by 8759d8c).

### CODE REVIEW

**Comment by willshen** [comment]
@martint good call. but to follow up on the TODO before we remove it, we should also remove `c == '<'`? assuming that is what @pnowojski meant in 3dbb3ba83dcbeed5faf490e34ebaed1398989f77 ?

**Comment by kokosing** [comment]
> we should also remove c == '<'

Piotr (pnowojski) is no longer working on Presto. I would try that, in worst case we will see the usage of it.

**Comment by willshen** [comment]
@kokosing yeah, also I see that the angle brackets are blocked already by:
```private static boolean validateName(String name)
    {
        return name.chars().noneMatch(c -> c == '<' || c == '>' || c == ',');
    }```
Seems to make sense to remove.

**Comment by willshen** [comment]
Oops I think that broke some stuff, for example, in one of the tests
```
[ERROR] testPathToRoot(io.prestosql.execution.resourcegroups.TestResourceGroupIntegration)  Time elapsed: 0.406 s  <<< FAILURE!

com.google.inject.CreationException: 

Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Bad type signature: 'map<varchar,varchar>'

  at io.prestosql.metadata.MetadataManager.<init>(MetadataManager.java:161)

  at io.prestosql.server.ServerMainModule.setup(ServerMainModule.java:349)

  while locating io.prestosql.metadata.MetadataManager

  at io.prestosql.server.ServerMainModule.setup(ServerMainModule.java:350)

  while locating io.prestosql.metadata.Metadata

    for the 1st parameter of io.prestosql.type.TypeDeserializer.<init>(TypeDeserializer.java:34)

  while locating io.prestosql.type.TypeDeserializer
```

**Comment by martint** [comment]
Yeah, it looks like there are some left-overs that call parse parseTypeSignature using angle brackets. That should be internal to the Presto codebase, though. Anything coming via the SQL parser should get normalized to parenthesis. So, it might be just a matter of fixing those references.

**Comment by willshen** [comment]
@martint gotcha. I will try to track down those internal references and fix them.

**Comment by willshen** [comment]
@martint other than MAP<> and ARRAY<>, I also saw references of `function<>` and `Classifier<>` that were failing. Should all <> be removed in general?

**Comment by martint** [comment]
Yes!

**Comment by willshen** [comment]
@martint I had to modify `presto-product-tests/conf/presto/etc/catalog/kafka/structural_datatype_avro.json` because it was failing the tests. Do you think this raise regression risk for users who may be using `<>` in their kafka schema json? This code path does not seem to be protected by the parser. Granted it was a deprecated legacy syntax, but it was still supported prior to this change.

**Comment by martint** [comment]
This syntax has been deprecated for years, so I don’t think it’s that big of a concern, especially since it only affects the Kafka configurations. Those should be fairly easy for someone to update when upgrading if they happen to be using the legacy syntax.

I’d be more concerned if we were talking about removing it from the SQL layer, as that would have to be done more carefully.

**Comment by willshen** [comment]
@martint Can you take a look again, and merge if this looks good to you? the tests that were failing now passed. However `TEST_SPECIFIC_MODULES=presto-hive` started failing, but upon triaging it seems related to failures already happening on master (see https://travis-ci.com/prestosql/presto/jobs/233894997)?

**Comment by martint** [comment]
Merged, thanks!

**Comment by willshen** [comment]
Thanks @martint for guiding this one through!

**Pull request merged**
