### PR TITLE
Use smaller table in testInsert and testCreateTableAsSelect

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
Might be useful to also do the same for `testCreateTableAsSelect`.

**Comment by losipiuk** [comment]
> Might be useful to also do the same for `testCreateTableAsSelect`.

Done @hashhar

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
> > Might be useful to also do the same for `testCreateTableAsSelect`.
> 
> Done @hashhar

please update cmt and pr title

**Review by hashhar — APPROVED** [review]

**Comment by losipiuk** [comment]
> please update cmt and pr title

commit was fine. PR updated.

**Comment by hashhar** [comment]
Nice, removed almost 10 minutes from every Hive job.

**Comment by losipiuk** [comment]
> Nice, removed almost 10 minutes from every Hive job.

All credit to you @hashhar and @jirassimok

**Pull request merged**
