### PR TITLE
Upgrade Elastic connector to 7.6.x

### PR DESCRIPTION
**Pull request by eskabetxe**
Update Elastic connector to last version of elastic

I test this changes against a 6.8.8 docker image and dont work because of breaking changes on 7
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html

should I create a presto-elasticseach7 ??

and maybe rename actual connector to presto-elasticsearch6, 
and create a presto-elasticsearch-base for common classes?

### CODE REVIEW

**Comment by martint** [comment]
What’s the motivation for this? The current connector should work with any version of elasticsearch above 6.0.0.

Splitting into multiple connectors is overkill and unnecessary, as there is no functionality in ES that one version of the connector would need to use or take advantage of that the other version wouldn’t.

**Comment by eskabetxe** [comment]
Hi @martint, there are a lot of changes from 6.0.0
from 6.3 some functionality from [X-Pack](https://www.elastic.co/what-is/open-x-pack) are free to use
[This PR](https://github.com/prestosql/presto/pull/1838) want to use that for example

After 7 we have some fields that we can map, like:
- [flattened](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html) this its like we have a JSON field

And some changes that we could use like [elasticsearch-sql](https://www.elastic.co/what-is/elasticsearch-sql), I think we could use this via REST api without problems (jbdc is license required)

**Comment by martint** [comment]
All those things can be implemented independently of updating the REST client. In the extreme case, we can implement the REST calls manually like we do for some of the APIs (e.g. the nodes and shards APIs, which are not implemented in the current version of the client)

The User Auth PR is purely at the Presto code level (it's actually a pretty trivial change). Support for `flattened` fields requires changing the way the query is built and how the results are decoded. I doubt we need a new version of the client for this.

**Comment by eskabetxe** [comment]
ok.. I close this..

**Comment by eskabetxe** [comment]
@martint how do we test fields added on version 7, like date_nanos or flattened..

its ok to duplicate tests to use a docker image with version 7.0.0 ??

**Comment by martint** [comment]
Yes, we should restructure the tests to be able to run them with various version of ES. It will require changes to ElasticsearchServer and TestElasticsearchIntegrationSmokeTest.

**Pull request closed without merging**
