### PR TITLE
Give Prometheus test classes meaningful names

### LINKED ISSUE #6059: Give Prometheus test classes meaningful names
`TestPrometheusIntegrationTests1`, `TestPrometheusIntegrationTests2`, `TestPrometheusIntegrationTests3`  are not the best names possible.

### PR DESCRIPTION
**Pull request by CoachLuck**
Fixes #6059 
* New pull request to fix incorrect issue assignment

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Thanks for fixing this. `#6048` is unrelated issue. Please remove the body and update the commit message as `Give Prometheus test classes meaningful names`

**Comment by CoachLuck** [comment]
> Thanks for fixing this. `#6048` is unrelated issue. Please remove the body and update the commit message as `Give Prometheus test classes meaningful names`

@ebyhr No problem, so would I have to go about creating a whole new PR with the new, correct, commit message?
First commit so still getting used to the issue manager, sorry about any issues this caused.

**Comment by ebyhr** [comment]
@CoachLuck You don't need to resend PR. Please remove the 2nd commit and fix the 1st commit message & body, then push a commit forcibly.

**Comment by ebyhr** [comment]
@CoachLuck Can you try these commands? The above "remove" meant drop (≠revert).
```bash
git rebase -i HEAD~3

# Editor will appear like this
pick a0c05096ca Give Prometheus test classes meaningful names (#6059)
pick a205549d79 Include full stacktraces from LogTestDurationListener test hang monitor
pick 28e59c06d6 Revert "Include full stacktraces from LogTestDurationListener test hang monitor"

# Edit three 'pick' with r, d, d and save
r a0c05096ca Give Prometheus test classes meaningful names (#6059)
d a205549d79 Include full stacktraces from LogTestDurationListener test hang monitor
d 28e59c06d6 Revert "Include full stacktraces from LogTestDurationListener test hang monitor"

# Next screen will be like this
Give Prometheus test classes meaningful names (#6059)

Fixes [#6048](https://github.com/prestosql/presto/issues/6059)
...

# Remove 'Fixes ...' line and remove ' (#6059)' and save
Give Prometheus test classes meaningful names

...

# Push
git push -f
...
```

**Comment by CoachLuck** [comment]
> @CoachLuck Can you try these commands? The above "remove" meant drop (≠revert).
> 
> ```shell
> git rebase -i HEAD~3
> 
> # Editor will appear like this
> pick a0c05096ca Give Prometheus test classes meaningful names (#6059)
> pick a205549d79 Include full stacktraces from LogTestDurationListener test hang monitor
> pick 28e59c06d6 Revert "Include full stacktraces from LogTestDurationListener test hang monitor"
> 
> # Edit three 'pick' with r, d, d and save
> r a0c05096ca Give Prometheus test classes meaningful names (#6059)
> d a205549d79 Include full stacktraces from LogTestDurationListener test hang monitor
> d 28e59c06d6 Revert "Include full stacktraces from LogTestDurationListener test hang monitor"
> 
> # Next screen will be like this
> Give Prometheus test classes meaningful names (#6059)
> 
> Fixes [#6048](https://github.com/prestosql/presto/issues/6059)
> ...
> 
> # Remove 'Fixes ...' line and remove ' (#6059)' and save
> Give Prometheus test classes meaningful names
> 
> ...
> 
> # Push
> git push -f
> ...
> ```

Just went through and did this. Didn't seem to give the desired outcome, but at least the original commit is correct.

**Comment by ebyhr** [comment]
> but at least the original commit is correct.

Expected status is one commit with `Give Prometheus test classes meaningful names` title. There are 5 commits now. 
https://github.com/prestosql/presto/pull/6230/commits

By the way, I sent Slack invitation so that we can talk quickly.

**Comment by CoachLuck** [comment]
> > but at least the original commit is correct.
> 
> Expected status is one commit with `Give Prometheus test classes meaningful names` title. There are 5 commits now.
> https://github.com/prestosql/presto/pull/6230/commits
> 
> By the way, I sent Slack invitation so that we can talk quickly.

Hey I got it, for some reason it didn't run correctly the first time around :) Thanks for the help!

**Comment by CoachLuck** [comment]
@ebyhr CLA finally has been registered :)

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
@CoachLuck Could you fix commit's email address? Currently, it starts with `beastlyaj01@`, but `ajiellodev@` is the expected  one.

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
