### PR TITLE
Using quotes with catalog/schema/table/... when reporting errors

### LINKED ISSUE #3006: Inconsistent error reporting when schema does not exist
```
presto> SELECT * FROM memory.xxx.yyy;
Query 20200305_113522_00005_kdbq9 failed: line 1:15: Schema xxx does not exist
```

```
presto> SHOW COLUMNS FROM memory.xxx.yyy;
Query 20200305_113603_00006_kdbq9 failed: line 1:1: Table 'memory.xxx.yyy' does not exist
```

```
presto> DESCRIBE memory.xxx.yyy;
Query 20200305_113620_00007_kdbq9 failed: line 1:1: Table 'memory.xxx.yyy' does not exist
```

Inconsistency:

* Error is about "Table does not exist" or "Schema does not exist"
* name is in apostrophes or not

### PR DESCRIPTION
**Pull request by emhlbmc**
Fix partially #3006

### CODE REVIEW

**Comment by sanchitkashyap** [comment]
This doesn't completely fix the issue, it doesn't address 

> More importantly, error is about "Table does not exist" vs "Schema does not exist".

**Comment by findepi** [comment]
@emhlbmc thanks, that was quick. 
Pleas check the test failures. I guess tests are asserting error messages and need to be updated as well.




> This doesn't completely fix the issue, it doesn't address
> 
> > More importantly, error is about "Table does not exist" vs "Schema does not exist".

@sanchitkashyap  correct, thanks for pointing this out!
i updated the PR desc so it doesn't close the referenced issue on merge

Let's keep those things in separate PRs for better reviewability.

**Comment by emhlbmc** [comment]
@cla-bot check

**Comment by martint** [comment]
@cla-bot check

**Comment by findepi** [comment]
Merged, thanks!

**Pull request closed without merging**
