### PR TITLE
Update docker images to version 34

### PR DESCRIPTION
**Pull request by kokosing**
Update docker images to version 34

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]

**Comment by wendigo** [comment]
```
io.prestosql.tests.hive.TestHiveTransactionalTable.testFilesForAbortedTransactionsIgnored (Groups: hive_transactional) took 15.5 seconds
2020-10-07T15:11:48.6605023Z tests               | 2020-10-07 20:56:48 SEVERE: Failure cause:
2020-10-07T15:11:48.6605674Z tests               | java.lang.AssertionError: Expected row count to be <4>, but was <6>; rows=[[1], [1], [1], [2], [2], [2]]
2020-10-07T15:11:48.6608345Z tests               | 	at io.prestosql.tests.hive.TestHiveTransactionalTable.testFilesForAbortedTransactionsIgnored(TestHiveTransactionalTable.java:427)
2020-10-07T15:11:48.6611645Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-07T15:11:48.6613654Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-07T15:11:48.6616021Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-07T15:11:48.6617745Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-07T15:11:48.6619320Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-10-07T15:11:48.6621015Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-10-07T15:11:48.6622811Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-10-07T15:11:48.6624486Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-10-07T15:11:48.6626520Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-10-07T15:11:48.6628530Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-10-07T15:11:48.6630385Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-07T15:11:48.6632433Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-07T15:11:48.6634237Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-07T15:11:48.6984244Z tests               | 
```

**Comment by kokosing** [comment]
@wendigo Are you familiar with this?

**Comment by wendigo** [comment]
> @wendigo Are you familiar with this?

No

**Comment by kokosing** [comment]
Captured this as https://github.com/prestosql/presto/issues/5463

**Pull request merged**
