### PR TITLE
Remove duplicate tpc-ds queries

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Review by findepi — APPROVED** [review]
https://github.com/prestosql/presto/blob/435de64ab9f1ae5a1bb51e6f0447a1dd6c89f8a1/presto-benchto-benchmarks/src/test/java/io/prestosql/sql/planner/TestTpcdsCostBasedPlan.java#L74

**Comment by findepi** [comment]
Update product tests too.

**Comment by sopel39** [comment]
@findepi which product tests?

**Comment by kokosing** [comment]
But these are not duplicate, these as variants. They are different.

**Comment by findepi** [comment]
> @findepi which product tests?

see https://github.com/prestosql/presto/tree/a6d9f2c5f818395b4fb3cc5ad53a88f3247caafb/presto-product-tests/src/main/resources/sql-tests/testcases/tpcds

**Comment by kokosing** [comment]
I would leave product tests as they are. Tests and benchmarks have different purpose.

**Comment by findepi** [comment]
> I would leave product tests as they are. Tests and benchmarks have different purpose.

In general i agree. However, the only reason we have these particular queries in product tests is because they are benchmark queries.

I am OK with leaving the test queries, but we should do something to avoid confusion and have single source of truth what are the queries we use for benchmarks

- in product tests, the retained variants should be renamed alike, for consistency with bencmarks
- the obsolete variants in benchmarks can stay in product tests but should be renamed to indicate that (eg q14_old_variant_2)

also, if product tests' versions and benchmark's versions have any other [allowed] differences, we should call them out too

(still, i'd just remove obsolete variants for simplicity)

**Comment by kokosing** [comment]
I am fine either way.

**Pull request merged**
