### PR TITLE
Verify schema exists for USE statement

### LINKED ISSUE #2763: Validate schema with use command
As discussed with @electrum and @martint on slack. 

https://prestosql.slack.com/archives/CFLB9AMBN/p1581114375346700

```
use tpch.foo 
```

should fail if the schema does not exist.

Just like

```
use foo.bar 
```

fails.

Connectors need to implement checkSchemaExists correctly for this to work

### PR DESCRIPTION
**Pull request by electrum**
Fixes #2763

### CODE REVIEW

**Comment by mosabua** [comment]
Nice!

**Comment by findepi** [comment]
@mosabua FYI i think you still can "enter" a schema that does not exist, via CLI --catalog,  --schema

**Comment by kokosing** [comment]
>  i think you still can "enter" a schema that does not exist, via CLI --catalog, --schema

Same applies to jdbc I guess.

**Comment by electrum** [comment]
@findepi I added an engine test

**Pull request merged**
