### PR TITLE
Add queryId to security contexts

### PR DESCRIPTION
**Pull request by kokosing**
Add queryId to security contexts

### CODE REVIEW

**Comment by kokosing** [comment]
FYI @martint

**Comment by martint** [comment]
There are compilation failures.

**Comment by kokosing** [comment]
Yes. It is WIP. I wanted to hear your opinion before I make it mergeable

**Comment by martint** [comment]
Looks reasonable to me.

**Comment by kokosing** [comment]
@martint I think this is ready to review.

**Pull request merged**
