### PR TITLE
WIP: Add array support using definitions in the _meta field.

### PR DESCRIPTION
**Pull request by brianolsen87**
Still needs a few more tests and discussion.

Fixes: #2441

### CODE REVIEW

**Comment by brianolsen87** [comment]
Just submitted my cla agreement.

**Comment by brianolsen87** [comment]
Not sure why but a hive test failed when all my changes were in presto-elasticsearch. 
https://github.com/prestosql/presto/pull/2462/checks?check_run_id=382764712#step:5:2608

Are these typical issues with the build or should I investigate this more?

**Comment by martint** [comment]
No, those are unrelated. There are some flaky tests we're trying to track down.

**Comment by martint** [comment]
@cla-bot check

**Comment by brianolsen87** [comment]
> Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Brian Olsen**.
> This is most likely caused by a git client misconfiguration; please make sure to:
> 
> 1. check if your git client is configured with an email to sign commits `git config --list | grep email`
> 2. If not, set it up using `git config --global user.email email@example.com`
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

hmm will I need to recommit after setting my email in the config?

**Comment by brianolsen87** [comment]
I was missing my credential information when submitting my commit. I just created an identical branch and resubmitted with the appropriate info and opened this PR. https://github.com/prestosql/presto/pull/2478

**Pull request closed without merging**
