### PR TITLE
Introduce hive.s3.local-endpoint

### PR DESCRIPTION
**Pull request by iirekm**
Rationale of this PR: 

In our integration tests (with TestContainers) MinIO and Hive run inside Docker containers, so the obvious way to initialize Presto/Hive would be something like this:
```java
.put("hive.s3.aws-access-key", MINIO_ACCESS_KEY)
.put("hive.s3.aws-secret-key", MINIO_SECRET_KEY)
 .put("hive.s3.endpoint", "http://minio:" + MINIO_PORT)
```

Unfortunately it doesn't work, because `hive.s3.endpoint` is used both by Hive container and `localhost` Presto, but in `localhost` both `minio` and `MINIO_PORT` aren't available. I've seen some ugly workarounds for this (like allocating hardcoded static ports on localhost + port forwarding), but they cause other problems (like unnecessary complexity or port conflicts).

So now we can use:
```java
.put("hive.s3.aws-access-key", MINIO_ACCESS_KEY)
.put("hive.s3.aws-secret-key", MINIO_SECRET_KEY)
.put("hive.s3.endpoint", "http://minio:" + MINIO_PORT)
.put("hive.s3.local-endpoint", "http://localhost:" + minioContainer.getMappedPort(MINIO_PORT))
```

Of course the old behavior still works: when `hive.s3.local-endpoint` is not given, `hive.s3.enpoint` is used for 'local` connection.

### CODE REVIEW

**Comment by losipiuk** [comment]
I am probably missing something but it looks like if the new `hive.s3.local-endpoint` is given then it will always be used. And the old `hive.s3.endpoint` property would just be ignored. Where is other place where `hive.s3.endpoint` is used apart from `PrestoS3ConfigurationInitializer.java`?

**Comment by iirekm** [comment]
As I wrote, it's passed also to hive container, this property is used for 2
different things

śr., 12 sie 2020, 12:58 użytkownik Łukasz Osipiuk <notifications@github.com>
napisał:

**Comment by losipiuk** [comment]
> As I wrote, it's passed also to hive container, this property is used for 2 different things

Could you link exactly where is the second use. I cannot find it by quickly greping codebase.

**Comment by iirekm** [comment]
I have no idea where it happens - it's done via Map of those hive.xxxx
properties, which is very hard to trace even under debugger, the only way
to reproduce it is via code:
- run Minio as Docker container (instead of AWS S3), forward Minio to
random localhost port
- run Hive as Docker container, forward Hive to random localhost ports
- run Presto on localhost together with Minio and Hive; Hive sees only
minio:<minio-port> or <minio-container-ip>:<minio-port>, Presto sees only
localhost:<forwarded-minio-port>

śr., 12 sie 2020 o 14:12 Łukasz Osipiuk <notifications@github.com>
napisał(a):

**Comment by iirekm** [comment]
there was some mess in our tests setup, luckily this change isn't needed so I'm closing it

**Comment by electrum** [comment]
Note that we have a similar problem for HDFS which is solved by the SOCKS proxy (ugly but unavoidable since it’s how HDFS works).

**Pull request closed without merging**
