### PR TITLE
Pushdown dereference expression to Parquet reader

### PR DESCRIPTION
**Pull request by JamesRTaylor**
Rebased @qqibrow [patch](https://github.com/prestosql/presto/pull/187) to Presto master. When querying nested data, this patch improved our performance 40x (120 seconds -> 3 seconds). Great work, @qqibrow!

### CODE REVIEW

**Comment by tooptoop4** [comment]
gentle ping

**Comment by tooptoop4** [comment]
rebase?

**Comment by tooptoop4** [comment]
@JamesRTaylor many conflicts

**Comment by martint** [comment]
This has already been merged as part of another PR.

**Pull request closed without merging**
