### PR TITLE
fix tpcds test results

### PR DESCRIPTION
**Pull request by yashaswaj**

### CODE REVIEW

**Comment by sopel39** [comment]
Were the tests failing?

**Comment by yashaswaj** [comment]
yes, these fail when i run locally, couldn't find tpcds in ci tests.

**Comment by kokosing** [comment]
> yes, these fail when i run locally, couldn't find tpcds in ci tests.

I think we need to restore these tpcds tests automation somewhere and then we could think about changing it. IIRC these tests were passing correctly, if you need to change the expected results then it might suggest a correctness bug in presto. 

Can you please add a tpcds test suite to: https://github.com/prestosql/presto/blob/master/.github/workflows/ci.yml#L176?

**Comment by yashaswaj** [comment]
Issue for q72 filed #4564 
q85 results fixed with #4446

**Pull request closed without merging**
