### PR TITLE
Add ExternalAuthorizer to JDBC

### PR DESCRIPTION
**Pull request by s2lomon**
This change adds possibility to utilize web-browser in authentication to Presto from jdbc and in feature from cli level. 

## Authentication Protocol

The modifications to the Presto client protocol (as defined here https://github.com/prestosql/presto/wiki/HTTP-Protocol) are fairly simple.  

The query submission `POST` to `/v1/statement` may fail with status `401 Unauthorized`:
```
WWW-Authenticate: Bearer [x_redirect_server="...",] x_token_server="..."
```
When a client gets this, the client should:
1. Open a web browser `x_redirect_server` URI if the field is present.
2. Polling the `x_token_server` URI until a bearer token is available or an error occurs.
3. Resubmit the query to `/v1/statement`, with the token in the header: 
```
Authorization: Bearer the-bearer-token-from-polling
```
Note: both of these URIs are absolute, so they should not be resolved.

## Token Polling

When polling the token address, the client should execute a request and when a the response is the following HTTP status code:
- `200 OK`: see below
- `3xx redirection`: Follow the redirects for the current request
- `503`: retry (same as client protocol)
- Other: Any other code should be treated as an error, and fail with an  “Unauthorized” message” (same as client protocol)

OK response body is one of the three following JSON documents:

**Success:** The authentication is complete and the token should be attached to all future query submission requests as a bearer token. Example:
```json
{
    "token" : "the-bearer-token"
}
```

**Not-ready:** The authentication is not complete. The client should immediately fetch the nextURI.  Example:
```json
{
    "nextUri" : "https://example.com/oauth/token/123456789"
}
```

**Error:** The authentication failed. The error message in the json document should be shown to the end user. Example:
```json
{
    "error" : "Authentication was canceled by the user"
}
```

This PR contains only the jdbc part, but I will be adding the required polling url soon.

### CODE REVIEW

**Comment by dain** [comment]
I suggest we document both urls are relative to the JDBC url..  That way either can be absolute or relative to make future changes easier.

Also, for the Token resource response codes, we should note the redirection response codes should be respected.  For `every other http code, will be recognized as a server error` does that mean the client should retry?

**Comment by kokosing** [comment]
This depends on https://github.com/prestosql/presto/pull/5355 (only the last commit matters).

**Comment by s2lomon** [comment]
@dain `I suggest we document both urls are relative to the JDBC url.. That way either can be absolute or relative to make future changes easier.` So I will call them redirectUrl and tokenUrl and will allow them to be relative or absolute. At the same time I would like to make the redirectUrl optional, for the flows that do not require redirections.

**Comment by s2lomon** [comment]
Since changes that this pr was dependent on has already been merged, I've created a new pr with updated protocol. #6196

**Pull request closed without merging**
