### PR TITLE
Test queries from documentation

### PR DESCRIPTION
**Pull request by kokosing**
[WIP] Test queries from documentation

### CODE REVIEW

**Comment by kokosing** [comment]
This is just a raw idea. Something to discuss.

**Comment by kokosing** [comment]
@mosabua long time ago I had an idea to make sure that all queries that are mentioned in the docs are tested. What do you think about that?

**Comment by mosabua** [comment]
In the long run doing something along these lines would be good. However I think at this stage we have a lot bigger problems to deal with in terms of documentation. So I suggest we just let this sit here

**Comment by mosabua** [comment]
And just do we don't loose track of it, I assigned the PR to myself for now.

**Comment by dain** [comment]
Let's close this for now.  When we get to this we'll open a new PR.

**Pull request closed without merging**
