### PR TITLE
Use Presto logo in project README.md file

### PR DESCRIPTION
**Pull request by raihan71**
## Summary
* Use Presto logo in project README.md file that makes nicer
* Changed position title and description Presto into the center

## Test Plan
<strong>Before</strong>

image

<strong>After</strong>

image

### CODE REVIEW

**Comment by electrum** [comment]
Thanks for helping to improve the README.

Since GitHub uses a white background, the middle part of the logo is not visible (it uses white dots). One of these might be better:
* https://github.com/prestosql/presto/blob/master/presto-docs/src/main/resources/logo/web/main/white/Presto_Logo_WhiteBG-01.svg
* https://github.com/prestosql/presto/blob/master/presto-docs/src/main/resources/logo/web/main/black/Presto_Logo_BlackBG-01.svg

**Comment by raihan71** [comment]
> Thanks for helping to improve the README.
> 
> Since GitHub uses a white background, the middle part of the logo is not visible (it uses white dots). One of these might be better:
> 
> * https://github.com/prestosql/presto/blob/master/presto-docs/src/main/resources/logo/web/main/white/Presto_Logo_WhiteBG-01.svg
> * https://github.com/prestosql/presto/blob/master/presto-docs/src/main/resources/logo/web/main/black/Presto_Logo_BlackBG-01.svg

Ohh yeah, thanks for the update, wait I'll fix it!

**Comment by kokosing** [comment]
Please make sure you file CLA, please follow: https://github.com/prestosql/cla. This is required in order to merge your change!

**Comment by raihan71** [comment]
> Please make sure you file CLA, please follow: https://github.com/prestosql/cla. This is required in order to merge your change!

I have already sent the CLA via email following https://github.com/prestosql/cla

**Comment by kokosing** [comment]
> I have already sent the CLA 

Great, we need to update then. Thanks!

**Comment by raihan71** [comment]
> > I have already sent the CLA
> 
> Great, we need to update then. Thanks!

Alright, thanks so much 🙏

**Comment by martint** [comment]
@cla-bot check

**Comment by raihan71** [comment]
Thank you for the invitation @martint @kokosing @electrum 🙏

**Comment by raihan71** [comment]
> Please squash all commits and use the below for the commit message:
> 
> ```
> Use Presto logo in project README.md file
> ```

done, can't wait to see its merged :)

**Comment by raihan71** [comment]
> LGTM, I will leave it open for a while to make sure all interested parties have a chance to comment.

Aa sure :)

**Comment by kokosing** [comment]
Merged, thanks!

**Pull request merged**
