### PR TITLE
Introduce Maven BOM for Presto

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
> This should probably be aligned with airlift by pulling in its equivalent with a scope=import. If structured correctly this can also be used by plugins, internal to the project or external

To me airlift is just a library that is used by Presto. Surely we can do it for airlift as well, but it is a bit independent from this.

**Comment by kokosing** [comment]
> We need to figure out the goal of the BOM and what we want it to contain.

@electrum What are your thoughts about it? My initial idea was to contain all presto modules and all dependencies that presto rely on. I think it is safe to limit BOM to contain all presto modules for now and then we can evaluate where to move further. How does it sound to you?

**Comment by electrum** [comment]
I don't think "all modules" is useful without considering the use case. For example, is the dependency for a connector the JAR, ZIP, both?

Aside from SPI and JDBC driver, none of these modules are libraries intended for external consumption. Testing infrastructure is somewhat of an exception, but it's a "use at your own risk" with no guarantees about stability, huge numbers of dependencies that can cause conflicts, etc. But then you also need the library dependencies.

**Comment by kokosing** [comment]
> Aside from SPI and JDBC driver, none of these modules are libraries intended for external consumption.

BOM that would contain only these few is not much useful. Closing for now.

**Pull request closed without merging**
