### PR TITLE
List schemas from current catalog only in Base JDBC client

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Comment by electrum** [comment]
Why not change to use the `getSchemas(catalog, schemaPattern)` variant, rather than filtering on the client side?

**Comment by sajjoseph** [comment]
I too have the same question as what David asked above.

If catalog value is present, the following code is expected to apply the filter. 
https://github.com/prestosql/presto/blob/8a9bcf0a98126fe1d3715ea0905ba83076669054/presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDatabaseMetaData.java#L1321

**Comment by sopel39** [comment]
> Why not change to use the getSchemas(catalog, schemaPattern) variant, rather than filtering on the client side?

@electrum you are right! I missed that method. Could you review again?

**Comment by tooptoop4** [comment]
@sopel39 does this fix https://github.com/prestodb/presto/issues/13122 ?

**Comment by findepi** [comment]
@tooptoop4 it is not related.

**Pull request merged**
