### PR TITLE
Add lake formation style authorization: external table locations must…

### PR DESCRIPTION
**Pull request by amiorin**
… be a subfolder of the schema location.

@findepi 
Hi Piotr,
I'm working on this pull request but I'm stuck on how to write the test. The FileHiveMetastore doesn't allow me to create a schema providing a location in the properties and if I try to create the schema in Java I got an error that I'm not in a transaction.

### CODE REVIEW

**Comment by findepi** [comment]
@amiorin would https://github.com/prestosql/presto/pull/1282 be helpful?

**Comment by findepi** [comment]
> The FileHiveMetastore doesn't allow me to create a schema providing a location in the properties 

every schema has a location (explicit or implicit), so you can define schema without one

also, FileHiveMetastore can be modified appropriately

> lake formation style authorization: external table locations must be a subfolder of the schema location.

that sounds like a surprising constraint, and kind of removes the point of using table locations & external tables.
Please confirm that simply disabling creation of external tables is not what you want.

(direct subfolder, or subfolder of any depth?)

**Comment by amiorin** [comment]
My 2 cents.
Hive compatibility is limiting Presto development IMO. I like the Drill approach to building a [new metastore](http://drill.apache.org/docs/drill-iceberg-metastore/) on top of Iceberg.

> > The FileHiveMetastore doesn't allow me to create a schema providing a location in the properties
> 
> every schema has a location (explicit or implicit), so you can define schema without one
> 
> also, FileHiveMetastore can be modified appropriately

I'll think about it.

> > lake formation style authorization: external table locations must be a subfolder of the schema location.
> 
> that sounds like a surprising constraint, and kind of removes the point of using table locations & external tables.
> Please confirm that simply disabling creation of external tables is not what you want.
> 
> (direct subfolder, or subfolder of any depth?)

Simply disabling the creation of external tables is not what I want. From Lake Formation [manual](https://docs.aws.amazon.com/lake-formation/latest/dg/lf-permissions-reference.html#perm-create-table).
Screenshot 2020-03-26 at 17 30 09
I've implemented use case 3. To implement use case 2 and 1, I need to alter the schema of HMS.

My plan is to have two Presto servers. One for queries and one for DDL statements. I'll fork the Hive connector and modify to achieve these goals:

1. Self-service create external tables.
2. Faster add and remove partitions with "alter table add partitions" and skipping the metastore and talking directly to MySQL.
3. Default permissions of create table that doesn't include [grantable = true](https://github.com/prestosql/presto/blob/047d75056b856a9d5090bb145c1bf338d2173ec9/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/MetastoreUtil.java#L286-L289).

**Comment by amiorin** [comment]
As in #3833, we are now evaluating to write an "admission controller" (the name comes from K8s) inside our Presto proxy. It will parse the query and reject queries that are not compliant. We don't need this PR anymore. Thank you for the review.

**Pull request closed without merging**
