### PR TITLE
Bump aws-sdk to 1.11.697

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/prestosql/presto/issues/2614 and https://github.com/prestosql/presto/issues/1132

### CODE REVIEW

**Comment by electrum** [comment]
@cla-bot check

**Comment by Praveen2112** [comment]
Can we remove the commits which are not required for this change ?

**Comment by sopel39** [comment]
please rebase

**Comment by tooptoop4** [comment]
@sopel39 rebased/squashed in https://github.com/prestosql/presto/pull/3016

**Pull request closed without merging**
