### PR TITLE
Add support for CREATE TABLE in Cassandra

### PR DESCRIPTION
**Pull request by ebyhr**

### CODE REVIEW

**Comment by findepi** [comment]
@ebyhr this one too -- https://github.com/prestosql/presto/blob/0c13d169dcf189d4a913187de6e33c212df92bfa/presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java#L163-L167

**Comment by ebyhr** [comment]
Unfortunately, we need to modify base `testDataMappingSmokeTest` due to `id` column name conflict. I only updated the TestCassandraDistributedQueries's comment in this PR.

**Comment by findepi** [comment]
@ebyhr if `id` is reserved in Cassandra, then sure, we can pick something else. Maybe `key`?
I went ahead and merged https://github.com/prestosql/presto/pull/3463 so please rebase. I think there is `id` there as well.

**Comment by ebyhr** [comment]
@findepi Rebased and confirmed `key` is fine as Cassandra column name. I'll look into the details so that we can enable it in the connector.

**Pull request merged**
