### PR TITLE
Free disk space before running product tests

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by electrum** [comment]
This saves 2.6G, which doesn't seem like a lot. I wonder where the rest is going.
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        84G   78G  5.4G  94% /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        84G   76G  8.0G  91% /
```

**Comment by martint** [comment]
> I wonder where the rest is going.

How big are the docker containers for all the connector tests and product tests?

**Comment by electrum** [comment]
The Maven install shouldn’t download any Docker containers. That happens when the product tests are run.

**Comment by martint** [comment]
What about all the testcontainers used in connector tests?

**Comment by electrum** [comment]
Those are independent jobs and not run as part of product tests.

**Pull request closed without merging**
