### PR TITLE
Fix punctuation in the Prometheus documentation

### PR DESCRIPTION
**Pull request by timflannagan1**
Fix punctuation in Prometheus documentation

### CODE REVIEW

**Comment by timflannagan1** [comment]
@refresh cla-bot

**Comment by timflannagan1** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
@cla-bot check

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
