### PR TITLE
Introduce Log function() conforming to SQL:2016

### PR DESCRIPTION
**Pull request by Praveen2112**
This patch adds the log function with arguments swapped and also removes the deprecated.legacy-log-function toggle.

Supersedes https://github.com/prestodb/presto/pull/12127. Fixes https://github.com/prestodb/presto/issues/12085

### CODE REVIEW

**Comment by martint** [comment]
@Praveen2112, there seem to be some build failures. Can you take a look?

**Comment by Praveen2112** [comment]
@martint I have updated the code and the build is success.

**Comment by findepi** [comment]
@martint this has been reviewed by @electrum under https://github.com/prestodb/presto/pull/12127

@Praveen2112 were there any code changes necessary when you rebased?

**Comment by Praveen2112** [comment]
@findepi Apart from the package name there wasn't much of a difference between the two PRs

**Comment by electrum** [comment]
One minor change: second commit needs to add docs for the new function. Otherwise ready to merge.

**Comment by martint** [comment]
@Praveen2112, can you address David's comment? I'll then go ahead and merge it.

**Comment by Praveen2112** [comment]
@electrum I ll update the docs

**Comment by Praveen2112** [comment]
@martint , @electrum I have added the new function in the log. Please let me know if there is any further changes.

**Pull request merged**
