### PR TITLE
Add support for Symlink Text InputFormat containing Parquet or Orc files

### PR DESCRIPTION
**Pull request by amiorin**
https://docs.databricks.com/delta/presto-compatibility.html#step-2-configure-prestoor-to-read-generated-manifests
https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-inventory.html#storage-inventory-athena-query

### CODE REVIEW

**Comment by electrum** [comment]
I'm not sure if this is all that is required to make this work. Can you add an integration test, probably in `presto-product-tests/src/main/java/io/prestosql/tests/hive`

**Comment by amiorin** [comment]
I'll fix it asap.

**Comment by electrum** [comment]
If you need help with adding a test for this, we can chat on Slack: https://prestosql.io/slack.html

**Comment by amiorin** [comment]
Not relevant anymore

**Pull request closed without merging**
