### PR TITLE
Verify GenericLiteral type in ExpressionVerifier

### PR DESCRIPTION
**Pull request by achyudh**
Fixes https://github.com/prestosql/presto/issues/3981

### CODE REVIEW

**Comment by achyudh** [comment]
Looks like the failing tests are due to case mismatch in the types (`BIGINT` vs `bigint`). Would comparing types with `equalsIgnoreCase` be the right thing to do here?

CLA: I sent a signed copy to cla@prestosql.io yesterday.

**Comment by findepi** [comment]
@achyudh `BIGINT` and `bigint` are the same type. However, in general, you cannot compare types
in the case-insensitive manner. An example would be a type that embodies an identifier, which can be
case sensitive if delimited -- `row("a" bigint)` and `row("A" bigint)` are not the same type.

Across code base, the `GenericLiteral` is commonly used to represent integer type literal (bigint, smallint, etc)
For these, case-insensitive comaprison is valid, but would require special-casing the types in `ExpressionVerifier`.

To avoid special-casing, I would recommend to do case-_sensitive_ comaprison (like you did)
and update those few failing test cases to use the required case (like change `bigint '5'` to `BIGINT '5'`).

**Comment by findepi** [comment]
CI failed -- https://github.com/prestosql/presto/issues/4169, rerunning

**Comment by achyudh** [comment]
@findepi Thanks for the clarification on the type comparison! I was looking into `TestHiveIntegrationSmokeTest.testCreatePartitionedBucketedTableAsFewRows` as the test was passing locally, didn't realize it was a CI issue.

**Comment by findepi** [comment]
@achyudh this is not precisely CI issue, it's a regression introduced last week and we are already working on a fix.

let me know if the build turns green now.

**Comment by achyudh** [comment]
@findepi `ci / pt (config-empty, suite-6-non-generic)` is still failing but the logs state that there were no failed tests: `Total tests run: 7, Failures: 0, Skips: 0`

**Comment by findepi** [comment]
Merged, thanks!

**Pull request merged**
