### PR TITLE
Allow JDBC based connector to define session properties

### PR DESCRIPTION
**Pull request by kokosing**
Allow JDBC based connector to define session properties

### CODE REVIEW

**Comment by findepi** [comment]
@kokosing this is already provided by https://github.com/prestosql/presto/pull/1148

**Comment by kokosing** [comment]
@findepi it was also provided with https://github.com/prestosql/presto/pull/1105 (Allow JDBC based connector to define session properties)

**Comment by findepi** [comment]
> @findepi it was also provided with #1105 (Allow JDBC based connector to define session properties)

oh, i missed that!

**Comment by findepi** [comment]
what's worse, i see now i've reviewed that code 😉

**Comment by kokosing** [comment]
😆

**Pull request closed without merging**
