### PR TITLE
Make the first characters of function description capitalized

### LINKED ISSUE #1983: Fix format for @Description value
Currently, the format of function description is varied as below (The first character uppercase/lowercase and the following period)
- `word_stem`: returns the stem of a word in the given language
- `zip`: Merges the given arrays, element-wise, into a single array of rows.

### PR DESCRIPTION
**Pull request by yuokada**
Resolve #1983

### CODE REVIEW

**Comment by ebyhr** [comment]
CI failure is related to this change. Please take a look at that. 
I guess you did grep with `@Description`, but some functions call `FunctionMetadata` directly (e.g. `MapTransformValuesFunction`) without the annotation.

**Comment by yuokada** [comment]
> I guess you did grep with @Description

Yeah, I did it.  I will fix.

**Comment by yuokada** [comment]
I assume we have to fix test cases for `tempto` like following differences.

```
diff --git presto-product-tests/src/main/resources/sql-tests/testcases/url_functions/checkUrlFunctionsRegistered.result presto-product-tests/src/main/resources/sql-tests/testcases/url_functions/checkUrlFunctionsRegistered.result
index 1b92cad01d..7fd044d55c 100644
--- presto-product-tests/src/main/resources/sql-tests/testcases/url_functions/checkUrlFunctionsRegistered.result
+++ presto-product-tests/src/main/resources/sql-tests/testcases/url_functions/checkUrlFunctionsRegistered.result
@@ -1,8 +1,8 @@
 -- delimiter: |; ignoreOrder: true; ignoreExcessRows: true; trimValues:true
- url_extract_fragment | varchar(x) | varchar(x) | scalar | true | extract fragment from url |
- url_extract_host | varchar(x) | varchar(x) | scalar | true | extract host from url |
- url_extract_parameter | varchar(x) | varchar(x), varchar(y) | scalar | true | extract query parameter from url |
- url_extract_path | varchar(x) | varchar(x) | scalar | true | extract part from url |
- url_extract_port | bigint | varchar(x) | scalar | true | extract port from url |
- url_extract_protocol | varchar(x) | varchar(x) | scalar | true | extract protocol from url |
- url_extract_query | varchar(x) | varchar(x) | scalar | true | extract query from url |
+ url_extract_fragment | varchar(x) | varchar(x) | scalar | true | Extract fragment from url |
+ url_extract_host | varchar(x) | varchar(x) | scalar | true | Extract host from url |
+ url_extract_parameter | varchar(x) | varchar(x), varchar(y) | scalar | true | Extract query parameter from url |
+ url_extract_path | varchar(x) | varchar(x) | scalar | true | Extract part from url |
+ url_extract_port | bigint | varchar(x) | scalar | true | Extract port from url |
+ url_extract_protocol | varchar(x) | varchar(x) | scalar | true | Extract protocol from url |
+ url_extract_query | varchar(x) | varchar(x) | scalar | true | Extract query from url |
\ No newline at end of file

```

**Comment by yuokada** [comment]
@ebyhr I've fixed test cases in TestShowQueries. Do I need to fix codes for `tempto` in order to fix CI build errors, too?

**Comment by ebyhr** [comment]
@yuokada Yes, it's required to pass tests.

**Comment by yuokada** [comment]
All checks were fixed.

**Comment by yuokada** [comment]
Fixed.

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
