### PR TITLE
Generate dynamic filters only during last PPD run

### PR DESCRIPTION
**Pull request by sopel39**
small one

### CODE REVIEW

**Comment by findepi** [comment]
Can you share the reason for this change?

**Comment by sopel39** [comment]
> Can you share the reason for this change?

There is no need to generate dynamic filtering in each PPD. It's enough that dynamic filters are pushed down in last PPD run. Otherwise it's just waste of CPU

**Comment by findepi** [comment]
DF are known to cause nice PPD-related side-effects:
https://github.com/prestosql/presto/blob/fa80b8d985abec4f1b6d99574fb8bc89b7adf45b/presto-main/src/test/java/io/prestosql/sql/planner/AbstractPredicatePushdownTest.java#L483

So you could want to run them as early as viable.
Inserting them in the last PPD run may miss some possible optimizations.

**Comment by sopel39** [comment]
> So you could want to run them as early as viable.
Inserting them in the last PPD run may miss some possible optimizations.

Mentioned TODO will happen regardless if you run DF early or late. At this point, if you add DF early in planning they will affect stats computations and reorder joins.
Additionally, DF are idempotent in a sense that no new information will be extracted if you add DF twice (the last run creates DFs that fit joins).
Therefore, adding DF twice doesn't bring any benefits, but adds to planning time

**Comment by findepi** [comment]
Thanks for explanation. 
I know DF negatively interacts with CBO and we already do not run them before RJ.
Remaining question would be -- does it make sense to add them as early as possible (still after RJ), or as late as possible?
As early seems better to me, but you chose as late as possible.
Then again, even if there is wasted CPU cycles, if this is overall negligible, we do not have to pick one.

whatever we settle on, it's important to capture the reasoning in a code comment.

**Comment by sopel39** [comment]
> As early seems better to me, but you chose as late as possible.
Then again, even if there is wasted CPU cycles, if this is overall negligible, we do not have to pick one.

If there is another PPD after DF are created, then such DFs might be invalidated by as equi-conditions could change. Therefore it makes sense to add DFs only during last PPD run and when joins are guaranteed not to change

**Comment by martint** [comment]
Please add the explanation to the commit message.

**Comment by sopel39** [comment]
@martint done

**Pull request merged**
