### PR TITLE
Parametrize Avro dependency version

### PR DESCRIPTION
**Pull request by medb**
This is useful when in custom build users want to change Avro version without editing source code.

### CODE REVIEW

**Comment by electrum** [comment]
Can you explain more about the specific motivations for this change? If there is a benefit to upgrading to a newer version, then we should update.

We normally only add version properties when there are multiple dependencies that need to share the same version.

**Comment by medb** [comment]
The motivation of this PR is to add a capability to build custom version of Presto with non-default Avro dependency (it could be higher or lower). This is useful when Presto build is part of a bigger build that includes many other OSS components. For example we build our own Hadoop, Hive and Presto and would like all of them to use the same dependencies that we deem important (file formats, for example). In such situations it's handy to have parametrized build that allow to override these dependencies without modifying source code.

**Comment by electrum** [comment]
The convention is important from a standpoint that this is non-standard, so it might get removed later when someone notices that it's only used in one place. We could address this with a comment, but that leads to the question of why certain dependencies are special in this way.

I'm more concerned about whether this is a reasonable thing to do. The version of dependencies chosen by Presto are an implementation detail. Two versions of Avro might be equivalent from Presto's perspective, as they only have changes in things not used by Presto, or the changes are inconsequential. If they are different in a user visible way, such as producing a file with different contents, then that's important, and we need to understand the consequences. For example, is the new format compatible with old readers? Do we have tests that cover this?

For these reasons, we don't want to encourage or tell people that it's ok to swap out the dependencies at build time. Changing the version is typically a small part of a larger change.

This might be better to discuss [Slack](https://prestosql.io/slack.html).

**Comment by medb** [comment]
This make sense, I will close PR then. Thanks for explanation!

**Pull request closed without merging**
