### PR TITLE
Use batch insert in Cassandra connector

### PR DESCRIPTION
**Pull request by ebyhr**
Introduced a property because Casandra throws following exception if the batch statements is too large (1,000 was invalid for tpch). 

  | Rows | Before | After (batch size: 100)
-- | -- | -- | --
customer | 1500 | 21.32s | 9.06s
orders | 15000 | 1.24m | 5.38s
lineitem | 60175 | 2.70m | 18.64s
part | 2000 | 4.93s | 1.71s
partsupp | 8000 | 22.73s | 2.23s
supplier | 100 | 741.17ms | 500.16ms
nation | 25 | 403.06ms | 494.67ms
region | 5 | 286.96ms | 576.63ms

```
com.datastax.driver.core.exceptions.InvalidQueryException: Batch too large
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at io.prestosql.plugin.cassandra.CassandraSession.lambda$execute$13(CassandraSession.java:443)
	at io.prestosql.plugin.cassandra.CassandraSession.executeWithSession(CassandraSession.java:538)
	at io.prestosql.plugin.cassandra.CassandraSession.execute(CassandraSession.java:443)
	at io.prestosql.plugin.cassandra.CassandraPageSink.finish(CassandraPageSink.java:189)
	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_testversion____20200901_145653_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### CODE REVIEW

**Comment by findepi** [comment]
> Introduced a property because Casandra throws following exception if the batch statements is too large (1,000 was invalid for tpch).

Can we do multiple batches when there are many rows?
like in JDBC -- https://github.com/prestosql/presto/blob/fd66bb72ddb9cfc311511900b1454cef385f172d/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcPageSink.java#L108-L113

**Comment by ebyhr** [comment]
@findepi I suppose the current implementation is already multiple batches. Or am I missing something?

**Comment by findepi** [comment]
@ebyhr sorry, didn't read the code, was just responding to your comment above.
Then why do we need a property?

**Comment by ebyhr** [comment]
@findepi The max batch size in Cassandra is small by default (50KB), so hard-coding may require Cassandra's reconfig and restart.

**Review by findepi — APPROVED** [review]

**Pull request merged**
