### PR TITLE
Keep query alive when the index is greater than array size

### PR DESCRIPTION
**Pull request by daikon12**
In my company, we use prestosql  315. 
We find that queries have frequently failed to execute recently .

The most important reason: "Array subscript out of bounds", This result is unfriendly to user.

Take an actual scenario:
The number of users whose favorite fruit is bananas

sql: select count(*) from userinfo where 'banana'= array_fruits[1];
array_fruits is a array which represents a list of favorite fruits in descending order

The query failed most of the time, Because some array_fruits information is empty.

Resolution :
when index is greater than array size return null, not a PrestoException .

So prestosql 315 can keep query alive when the index is greater than array size, then do some other logic of the query.
In addition，there are lower usage costs for analysts who are from Hive to Presto

### CODE REVIEW

**Comment by daikon12** [comment]
> Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **[daikai@oppo.com](mailto:daikai@oppo.com)**.
> This is most likely caused by a git client misconfiguration; please make sure to:
> 
> 1. check if your git client is configured with an email to sign commits `git config --list | grep email`
> 2. If not, set it up using `git config --global user.email email@example.com`
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

Thx , done

**Comment by findepi** [comment]
I guess the implemented semantics are aligned with the SQL spec but I defer to @martint on that.

@daikon12 would you consider using `element_at` in your queries?
```
presto:default> SELECT element_at(ARRAY[], 3);
 _col0
-------
 NULL
(1 row)
```

**Comment by daikon12** [comment]
> I guess the implemented semantics are aligned with the SQL spec but I defer to @martint on that.
> 
> @daikon12 would you consider using `element_at` in your queries?
> 
> ```
> presto:default> SELECT element_at(ARRAY[], 3);
>  _col0
> -------
>  NULL
> (1 row)
> ```

Thanks for your reply，element_at works.
Compared with array subscripts, element-at need to cultivate more analysts' habits, .
It would be better if presto gives  more consideration to compatibility.

**Comment by martint** [comment]
> I guess the implemented semantics are aligned with the SQL spec but I defer to @martint on that.

Correct. The SQL specification requires that array subscript fail with an error if the index is out of bounds. That's why we introduced `element_at` as an alternative that doesn't fail. From the spec:

```
a) If i is greater than zero and less than or equal to the cardinality of
   <array value expression>, then the result of <array element reference> 
   is the value of the i-th element of the value of <array value expression>.
b) Otherwise, an exception condition is raised: data exception — array element error.
```

**Comment by daikon12** [comment]
> > I guess the implemented semantics are aligned with the SQL spec but I defer to @martint on that.
> 
> Correct. The SQL specification requires that array subscript fail with an error if the index is out of bounds. That's why we introduced `element_at` as an alternative that doesn't fail. From the spec:
> 
> ```
> a) If i is greater than zero and less than or equal to the cardinality of
>    <array value expression>, then the result of <array element reference> 
>    is the value of the i-th element of the value of <array value expression>.
> b) Otherwise, an exception condition is raised: data exception — array element error.
> ```
  @martint @findepi Thanks， I understand your original design for ArraySubscriptOperator better.

**Comment by sopel39** [comment]
@daikon12 Could you try using `TRY` operator in Presto? See: https://prestodb.github.io/docs/current/functions/conditional.html

```
select count(*) from userinfo where 'banana'= try(array_fruits[1]);
```

If it doesn't work, we could add capture of `Array subscript out of bounds` errors in `TRY` operator.

**Pull request closed without merging**
