### PR TITLE
Add Alluxio to Hive Connector doc

### PR DESCRIPTION
**Pull request by apc999**
Create a new PR to incorporate feedbacks in https://github.com/prestosql/presto/pull/1464/.

### CODE REVIEW

**Comment by ebyhr** [comment]
@apc999 Have you seen https://github.com/prestosql/presto/pull/1464?

**Comment by apc999** [comment]
@electrum Please take a look

**Comment by apc999** [comment]
@electrum any feedback here?

**Comment by electrum** [comment]
Merged, thanks!

**Comment by electrum** [comment]
Merged as 6fe083ba3689701c417f9d2bf1b3da78ac705feb

**Pull request closed without merging**
