### PR TITLE
Aggregation pushdown for SQL Server

### LINKED ISSUE #4139: Aggregation pushdown in SQL Server connector
Follow-up to https://github.com/prestosql/presto/pull/3881

Relates to: https://github.com/prestosql/presto/issues/4138

### PR DESCRIPTION
**Pull request by mr-big-spency**
Resolve #4139

### CODE REVIEW

**Comment by findepi** [comment]
Can you please squash & rebase? There is a conflict which prevents CI from running on your PR.

**Comment by mosabua** [comment]
Can you please add the relevant user facing documentation similar to e.g. https://prestosql.io/docs/current/connector/postgresql.html#pushdown

**Comment by mr-big-spency** [comment]
> Can you please squash & rebase? There is a conflict which prevents CI from running on your PR.

yes.  will do shortly.

**Comment by mr-big-spency** [comment]
> Can you please squash & rebase? There is a conflict which prevents CI from running on your PR.

yes.  will do shortly.

> Can you please add the relevant user facing documentation similar to e.g. https://prestosql.io/docs/current/connector/postgresql.html#pushdown

yes.  will do.  this is my first contribution... there must be a .md file to update for this release right?

**Comment by mosabua** [comment]
Doc file to update it https://github.com/prestosql/presto/blob/master/presto-docs/src/main/sphinx/connector/sqlserver.rst

And with regards to release notes.. that is assembled later.

**Comment by martint** [comment]
@cla-bot check

**Review by aalbu — COMMENTED** [review]
LGTM

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
merged as 5bdd1c14ec1170a9885debf6dc310da9b1e1cd15, thanks!

**Pull request closed without merging**
