### PR TITLE
fix typo in json property

### PR DESCRIPTION
**Pull request by hgschmie**

### CODE REVIEW

**Comment by hgschmie** [comment]
I have to admit that it is not clear to me how the tests using this class ever passed. They fail for me if I run them locally on the hive connector repo (and yet the full build passes).

**Comment by findepi** [comment]
`TestRecordingHiveMetastore` passes for me locally -- before & after the change.

> They fail for me if I run them locally

interesting. Do you have a stacktrace to share?

**Comment by hgschmie** [comment]
so this is an interesting problem. tl;dr: this works through magic. :-) 

The regular build uses the `<parameters>true</parameters>` setting, which make this work, even with the typo. The bean serializer does some magic and writes the recording file like this:

```
"grantedPincipals" : [ {
    "key" : "role",
    "value" : [ {
      "grantee" : {
        "type" : "USER",
        "name" : "grantee"
      },
      "roleName" : "role",
      "grantable" : true
    } ]
  } ]
```

Note that there is the typo in the `grantedPincipals`. Somehow, by looking at parameters, Jackson has discovered bean properties with that name, even though it is only mistyped in the annotation for the constructor argument. 

What happened for me was that I had loaded presto into IntelliJ and the compliation configuration got out of sync with maven and it was missing the `-parameters` from the Preferences -> Java Compiler -> Override compiler parameters per-module. 

Now running the exact same test writes a recording file that looks like this:
 
```
"grantedPrincipals" : [ {
    "key" : "role",
    "value" : [ {
      "grantee" : {
        "type" : "USER",
        "name" : "grantee"
      },
      "roleName" : "role",
      "grantable" : true
    } ]
  } ]
```

Jackson now picks up the property name from the annotated getter (`@JsonProperty`) and calls it correctly `grantedPrincipals` from the name of the method. Trying to load this back in now hits the constructor parameter with the incorrectly annotated name (`@JsonProperty("grantedPincipal")`), therefore passes in a null and getting this NPE:

```
java.lang.NullPointerException
	at io.prestosql.plugin.hive.metastore.RecordingHiveMetastore.toMap(RecordingHiveMetastore.java:186)
	at io.prestosql.plugin.hive.metastore.RecordingHiveMetastore.loadRecording(RecordingHiveMetastore.java:139)
	at io.prestosql.plugin.hive.metastore.RecordingHiveMetastore.<init>(RecordingHiveMetastore.java:113)
	at io.prestosql.plugin.hive.metastore.TestRecordingHiveMetastore.testRecordingHiveMetastore(TestRecordingHiveMetastore.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

You can reproduce this by removing the `-parameters` setting from the module in IntelliJ or by renaming the parameter name in line 575 to `@JsonProperty("grantedPincipals") List<Pair<String, Set<RoleGrant>>> grantedPincipals)`

This is basically a quirk (and a correctness fix) in the way Jackson works. As the code base is compiled with parameters, it may actually be a better fix to remove all the Json Properties (the `@JsonCreator` annotation on the method suffices).

**Comment by findepi** [comment]
Thanks @hgschmie for the analysis! That makes total sense.

> As the code base is compiled with parameters, it may actually be a better fix to remove all the Json Properties (the @JsonCreator annotation on the method suffices).

We didn't do this initially when adding `-parameters` because it was unreliable at first, etc.
It seems OK to me to remove them, but would like to hear others opinion first, before doing this.
Especially that this is a lot of code changes in total.

so -- @electrum @dain @sopel39 @kokosing?

**Comment by kokosing** [comment]
👍 For more reliable way that requires less code.

**Comment by findepi** [comment]
@hgschmie would you like to create an issue to track this?

**Comment by dain** [comment]
> We didn't do this initially when adding `-parameters` because it was unreliable at first, etc.
> It seems OK to me to remove them, but would like to hear others opinion first, before doing this.
> Especially that this is a lot of code changes in total.
> 
> so -- @electrum @dain @sopel39 @kokosing?

My guess is @martint  will be opinionated about this.  I'm ok with what ever you all decide... the annotations don't seem bad to me, but not having them would be fine also.

**Pull request merged**
