### PR TITLE
Use unique table name in test

### PR DESCRIPTION
**Pull request by kokosing**
Use unique table name in test

### CODE REVIEW

**Comment by kokosing** [comment]
> however, in this class there are more test methods which CT

I know. So far other methods were not causing any issues.

**Comment by kokosing** [comment]
Unfortunately there are more issues: https://github.com/prestosql/presto/pull/3346

**Comment by findepi** [comment]
> 
> I know. So far other methods were not causing any issues.


that's just random

**Comment by kokosing** [comment]
> that's just random

Almost, there are some very likely patterns. Test from this PR was failing like almost, and other tests were failing like never.

**Pull request merged**
