### PR TITLE
Bump Rubix version to 0.3.15

### PR DESCRIPTION
**Pull request by losipiuk**
New version is a bugfix release. Among other it includes fix for #3580

### CODE REVIEW

**Comment by wendigo** [comment]
What does is bring @losipiuk  ?

**Comment by losipiuk** [comment]
> What does is bring @losipiuk ?

Bugfixes. Specifically one regarding Rubix misbehavior with limited caching space. 
I still want to give it a bit testing before merging. Tagging as WIP.

**Comment by losipiuk** [comment]
I run the build with update version through benchmarks and worked fine.

**Comment by losipiuk** [comment]
@findepi @stagraqubole :)

**Comment by stagraqubole** [comment]
@losipiuk I just found https://github.com/qubole/rubix/pull/431 yesterday, it had quite an impact on some tpcds queries. I will make a release with that change, it would be better to upgrade to 0.3.14

**Comment by losipiuk** [comment]
> @losipiuk I just found [qubole/rubix#431](https://github.com/qubole/rubix/pull/431) yesterday, it had quite an impact on some tpcds queries. I will make a release with that change, it would be better to upgrade to 0.3.14

Cool. Let me know when release is made. I will run some benchmarks too, and update this PR.

**Comment by findepi** [comment]
Quoting https://github.com/qubole/rubix/pull/431

> Avoid extra getFileStatus call in listLocatedStatus 
>
> Existing `getFileBlockLocations(Path p, long start, long len)` makes `getFileStatus(p)` to get the fileStatus to pass into `getFileBlockLocations(FileStatus file, long start, long len)` which is unnecessary and causes extra cloud store calls slowing down the split generation

It could be possible to not only rely on benchmarks for things like that.
For example, one can use MinIO docker container and utilize API call metrics
provided by MinIO. This way, performance-sensitive aspects of code behavior
can be tested as part of regular integration tests.

**Comment by losipiuk** [comment]
> Quoting [qubole/rubix#431](https://github.com/qubole/rubix/pull/431)
> 
> > Avoid extra getFileStatus call in listLocatedStatus
> > Existing `getFileBlockLocations(Path p, long start, long len)` makes `getFileStatus(p)` to get the fileStatus to pass into `getFileBlockLocations(FileStatus file, long start, long len)` which is unnecessary and causes extra cloud store calls slowing down the split generation
> 
> It could be possible to not only rely on benchmarks for things like that.
> For example, one can use MinIO docker container and utilize API call metrics
> provided by MinIO. This way, performance-sensitive aspects of code behavior
> can be tested as part of regular integration tests.

Are you suggesting the testing within Presto or Rubix itself?

**Comment by findepi** [comment]
> Are you suggesting the testing within Presto or Rubix itself?

I do not know the details of Presto-Rubix integration to make the call.
I think you @losipiuk @sopel39 @stagraqubole are in a better position to decide that.

**Comment by losipiuk** [comment]
> > Are you suggesting the testing within Presto or Rubix itself?
> 
> I do not know the details of Presto-Rubix integration to make the call.
> I think you @losipiuk @sopel39 @stagraqubole are in a better position to decide that.

If rubix (or hadoop) is already exposing JMX statistics which map to `getFileStatus` calls when reading from `CachingLocalFileSystem` it should easy to extend [TestRubixCaching](https://github.com/prestosql/presto/blob/889298f271c33982690fb0b2d45bd2d6e16d6ce4/presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java). Otherwise (which is probably the case) we would need to make test more complex, for example following approach @findepi suggested.

Yet still it feels to me that this aspect is too much implementation detail of Rubix, to be tested in Presto. And I would prefer to have integration test of that on Rubix side. WDYT @stagraqubole ?

**Comment by stagraqubole** [comment]
Agreed that this should be covered on Rubix side. We currently run tpcds suite once in a couple of releases, we plan to create a regression suite out of this that can be run every release. That should give us coverage against most of the bugs like this one. Granular testing, at the api metrics level like @findepi has suggested, would be good to find issues that can go unnoticed in perf testing, I will track this in Rubix repo.

**Comment by losipiuk** [comment]
@stagraqubole I see that there is rubix 0.3.15 released already. Can you confirm that that release is production quality and we can proceed with bumping version in Presto?

**Comment by stagraqubole** [comment]
@losipiuk yes, it is ready for use, we can upgrade to 0.3.15

**Pull request closed without merging**
