### PR TITLE
Introduce preparing query state

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
Fixes https://github.com/prestosql/presto/issues/545

Query is in state `PREPARING`, before it gets into a queue. By `PREPARING` all the work that is needed to ensure that query is eligible to be queued (like semantic analysis). There are cases where semantic analysis require non trivial amount of time. Thanks to this change it will be easy for user how much time semantic analysis took and how much time query was actually queued.

Additionally, I allowed query that was not yet added to query manager to be killed and displayed in UI and from `system.runtime.queries`.

**Comment by dain** [comment]
Analysis now happens in a background thread, so the query can begin queueing before analysis is complete:

https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQueryFactory.java#L112-L119

I don't think this can be modeled in the existing state machine code which requires state to be sequential.  Also with remote dispatcher the analysis can happen multiple times on different coordinators.  If the goal is to simply measure analysis time, I believe we already have dedicated counters for this.

BTW, other than parsing and resource group selection, the query is immediately placed in the queue, and available to be killed.

**Comment by dain** [comment]
BTW, I just spend ages removing unnecessary complexity and fixing bugs in this part of the code for the dispatcher project, so I'm concerned about any possible new unnecessary complexities.

**Comment by sopel39** [comment]
> Analysis now happens in a background thread, so the query can begin queueing before analysis is complete:

Would it be possible to cancel analysis once query is in the queue?

**Comment by dain** [comment]
> > Analysis now happens in a background thread, so the query can begin queueing before analysis is complete:
> 
> Would it be possible to cancel analysis once query is in the queue?

Analysis is a single threaded process that doesn't check query state.  I think the best we could do is to interrupt the thread by canceling the future.

**Comment by kokosing** [comment]
Replaced with #1079 and #1084

**Pull request closed without merging**
