### PR TITLE
Remove TestUninterruptably

### PR DESCRIPTION
**Pull request by kokosing**
Remove TestUninterruptably

This is not needed as one can add --debug to product test launcher to
avoid interrupting docker execution.

### CODE REVIEW

**Comment by skrzypo987** [comment]
> This is not needed as one can add --debug to product test launcher to
> avoid interrupting docker execution.

Standard question - Is it described anywhere? If so then you have my blessing

**Comment by kokosing** [comment]
> Standard question - Is it described anywhere? If so then you have my blessing


https://github.com/prestosql/presto/commit/d22c4fd2076b1fceb5367a91fe64b1aa288fe46f

**Comment by kokosing** [comment]
It looks like https://github.com/prestosql/presto/tree/master/presto-product-tests/README.md is still outdated and there is no mention about --debug switch at all.

**Review by zaz968m — APPROVED** [review]
It's dead class, so I don't see a reason not to approve.

**Review by findepi — APPROVED** [review]
thanks

**Review by djsstarburst — APPROVED** [review]
The benefit of the tiny static method TestUninterruptably is that the system will pause even if there are exceptions thrown.  I'm not sure why it's so important to remove this seemingly inoffensive static class, but if it's thought important, I don't object to removing it.

**Comment by kokosing** [comment]
This class is not used. To use it one needs to modify the code. If needed one can write this if needed.

**Pull request merged**
