### PR TITLE
Define timeouts for CI jobs

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by findepi** [comment]
30, 60, 75 -- how did you pick the values?

**Comment by losipiuk** [comment]
> 30, 60, 75 -- how did you pick the values?

I went through green run and picked values based on actual runtime. If I did not mess up each timeout is at least 20mins above runtime.

**Review by wendigo — APPROVED** [review]

**Review by findepi — APPROVED** [review]
i am fine, but 75 is concerningly high.

**Comment by losipiuk** [comment]
> i am fine, but 75 is concerningly high.

There is 120 even for (PT).

Generally the high number comes from the we use matrix test definition. For most jobs much smaller value would be enough. But there were one or two which took ~50 mins.

**Comment by losipiuk** [comment]
> > i am fine, but 75 is concerningly high.
> 
> There is 120 even for (PT).
> 
> Generally the high number comes from the we use matrix test definition. For most jobs much smaller value would be enough. But there were one or two which took ~50 mins.

I looked once again for this run. And the slowest (presto-tests) was 40 mins. So I guess 60 min timeout will be fine. WIll change

**Pull request merged**
