### PR TITLE
SImplify benchmark block serde

### PR DESCRIPTION
**Pull request by skrzypo987**
This PR consists of first two commits of https://github.com/prestosql/presto/pull/6077

### CODE REVIEW

**Review by sopel39 — APPROVED** [review]

**Comment by sopel39** [comment]
Should we add test case for all null case?

**Comment by skrzypo987** [comment]
> Should we add test case for all null case?

Isn't the whole block empty then? That will be pretty fast though

**Comment by sopel39** [comment]
> Isn't the whole block empty then? That will be pretty fast though

Indeed. Let's skip it then

**Comment by sopel39** [comment]
merged, thanks!

**Pull request merged**
