### PR TITLE
Eliminate view owner identity leak with Access Denied message

### PR DESCRIPTION
**Pull request by ssheikin**
Commit af4a6900aa58f170ee204b4216895c0c3f7ada07 reverted

### CODE REVIEW

**Review by kokosing — APPROVED** [review]

**Comment by willmostly** [comment]
Presto does not support any method for checking the ownership of a view. If the error message is reduced to "View owner cannot select from ...", how can this information be acted upon?

**Comment by kokosing** [comment]
> Presto does not support any method for checking the ownership of a view.

Would logging such information to server log on debug level be sufficient to you?

**Comment by willmostly** [comment]
> > Presto does not support any method for checking the ownership of a view.
> 
> Would logging such information to server log on debug level be sufficient to you?

Yes that would be sufficient. Something like Hive's `describe extended` would be ideal eventually :)

**Comment by kokosing** [comment]
>  Something like Hive's describe extended would be ideal eventually :)

What do you mean by that? Would you like to modify Presto `SHOW CREATE TABLE`? What kind of information are you for? To check the view owner?

**Comment by willmostly** [comment]
Hive's `EXTENDED` option will show the owner of the table/view, as well as create time and last access time.

**Comment by zaz968m** [comment]
https://github.com/starburstdata/starburst-presto/pull/1259#discussion_r500942768 has to be addressed as well

**Comment by ebyhr** [comment]
@zaz968m Could you rebase on upstream to resolve conflicts?

@willmostly There is a special table `<table>$prorperties` to expose Hive properties. 
https://prestosql.io/docs/current/connector/hive.html#table-properties

**Comment by kokosing** [comment]
@ebyhr does `table$properties` expose information about ownership?

**Comment by ebyhr** [comment]
@kokosing No, the table doesn't expose owner and a view doesn't have the special table.

**Pull request closed without merging**
