### PR TITLE
Convert all code-block:: none to c-b:: text

### PR DESCRIPTION
**Pull request by Ordinant**
Research determined that none  is not a supported argument for the Sphinx code-block: directive. To have Sphinx apply no source code coloring, use code-block: text. This was determined when trying to use the doc8 command line tool to validate RST files.

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
Great little catch and fix. It's a simple search replace and ensures the usage is now valid. We should merge asap to reduce any churn.

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by electrum** [comment]
This change contradicts the Sphinx documentation: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#showing-code-examples

**Comment by mosabua** [comment]
@electrum it does not contradict the docs at all. It says there "and any other lexer alias that Pygments supports". 

text is the lexer alias for no highlighting and changing to this allows us to validate docs with doc8 better. Changing makes it easier for doc writers using validator and has no negative impact on the output.

**Pull request merged**
