### PR TITLE
Do not filter out existing compactions in TestHiveTransactionalTable

### PR DESCRIPTION
**Pull request by losipiuk**
Temporary workaround to  hopefully fix https://github.com/prestosql/presto/issues/4089

### CODE REVIEW

**Comment by findepi** [comment]
We need a code comment for this. 

Did you try repro this locally?
Maybe we should be setting `NO_AUTO_COMPACTION` tblproperties ?
https://cwiki.apache.org/confluence/display/Hive/Hive+Transactions#HiveTransactions-TableProperties

**Comment by losipiuk** [comment]
> We need a code comment for this.

I will let the CI run. If we decide to merge it I will add comment before merging.

> 
> Did you try repro this locally?

NO that is a blind shot.

> Maybe we should be setting `NO_AUTO_COMPACTION` tblproperties ?
> https://cwiki.apache.org/confluence/display/Hive/Hive+Transactions#HiveTransactions-TableProperties

That is a good idea. Unless we have auto compaction disabled globally in our images. I asked that question to @wendigo and he is checking what is the state.

**Comment by findepi** [comment]
> Unless we have auto compaction disabled globally in our images

I do not think we have.... OTOH i was sure i used `NO_AUTO_COMPACTION` somewhere, but can't find it... So worth double checking.

**Comment by wendigo** [comment]
@losipiuk @findepi `hive.compactor.initiator.on` is on on HDP3.1 but it's not set on HDP2.6 (so I guess off by default)

**Comment by wendigo** [comment]
I'm in favour of disabling auto compactions on out test tables and leave HDP configuration as-is.

**Comment by findepi** [comment]
> `hive.compactor.initiator.on` is on on HDP3.1 but it's not set on HDP2.6

@wendigo transactional tables are not supported with HDP2.6, this test is not run against that env

**Comment by wendigo** [comment]
@findepi makes sense

**Comment by losipiuk** [comment]
https://github.com/prestosql/presto/pull/4093 is less agressive and seem to fix the issue https://github.com/prestosql/presto/pull/4093

**Pull request closed without merging**
