### PR TITLE
Pattern matching refactor and removal of PlanNodeMatcher

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
Copy of https://github.com/prestodb/presto/pull/9787. 

This probably still needs to be polished after the rebase.

**Comment by kokosing** [comment]
The origin PR was approved by @sopel39, I only rebased since then.

@findepi @martint @sopel39  Anyone wants to take a look before merging?

**Comment by sopel39** [comment]
Why it didn't land previously?

**Comment by kokosing** [comment]
> Why it didn't land previously?

I do not remember exactly. I think I was waiting to get more approvals.

**Pull request merged**
