### PR TITLE
Register partition from default location when location is missing in registerPartition procedure

### PR DESCRIPTION
**Pull request by wendigo**
Fixes https://github.com/prestosql/presto/issues/4443

### CODE REVIEW

**Comment by wendigo** [comment]
Probably needs documenting but I don't know the convention for optional arguments in procedures. Calling @mosabua

**Comment by findepi** [comment]
Not sure if we need this (`syntax-needs-review`) -- https://github.com/prestosql/presto/issues/4443#issuecomment-658725826

**Comment by mosabua** [comment]
I think we just document all signatures as separate choices with the same name and then link them together in the description. At least I have seen that for datetime stuff. Not sure there is really a convention just yet .. @electrum ?

**Comment by findepi** [comment]
> Will wait some time to see whether anyone has any other concerns.

David approved the concept in https://github.com/prestosql/presto/issues/4443#issuecomment-659732779

**Comment by findepi** [comment]
Merged, thanks!

**Comment by findepi** [comment]
@mosabua can you take care of the docs change?
or tell @wendigo how this should look like?

**Comment by wendigo** [comment]
@findepi I'll open PR with a doc update

**Comment by mosabua** [comment]
Thanks @wendigo  .. add me as reviewer.

**Pull request merged**
