### PR TITLE
Fix imports

### PR DESCRIPTION
**Pull request by oneonestar**
Fix minor import issue from #3771

### CODE REVIEW

**Comment by findepi** [comment]
@oneonestar there are `alluxio.shaded.` in other classes too.
Maybe we can have a checkstyle rule too?

**Comment by losipiuk** [comment]
> @oneonestar there are `alluxio.shaded.` in other classes too.
> Maybe we can have a checkstyle rule too?

Yeah - though of that too. I think we have some rules which perform checks like this already. Are they checkstyle based or is it some other mechanism?

**Comment by findepi** [comment]
Sorry, wrong advice. We have https://github.com/airlift/airbase/blob/master/airbase-policy/src/main/resources/checkstyle/airbase-checks.xml
but it's not suitable for Presto-specific rules.

it would be good have Presto-specific rules too, but let's leave this as a follow-up to this PR.

@oneonestar can you please update other classes too?

**Comment by oneonestar** [comment]
https://github.com/prestosql/presto/blob/67368f6a033176b37c6264912751a00c04b51707/presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/alluxio/TestingAlluxioMetastoreObjects.java#L29
https://github.com/prestosql/presto/blob/cbf0d04b766d7a90c69e8dd7bc18a48779441749/presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/alluxio/TestProtoUtils.java#L17
https://github.com/prestosql/presto/blob/67368f6a033176b37c6264912751a00c04b51707/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/alluxio/ProtoUtils.java#L30

I found 3 usages in the code, but they are all related to Alluxio:
`alluxio.grpc.table.Layout::setLayoutData()` takes `alluxio.shaded.client.com.google.protobuf.ByteString`.

`alluxio.table.ProtoUtils.toHiveLayout()` throws `alluxio.shaded.client.com.google.protobuf.InvalidProtocolBufferException`.

I don't think we can fix these unless the Alluxio lib stop using shaded protobuf.

**Comment by findepi** [comment]
> `alluxio.table.ProtoUtils.toHiveLayout()` throws `alluxio.shaded.client.com.google.protobuf.InvalidProtocolBufferException`.

@apc999 can this be fixed?

**Comment by findepi** [comment]
Merged, thanks!

**Pull request merged**
