### PR TITLE
[FIX-Bug #5998][SystemConnector] NotInTransactionException: Unknown transaction ID because of multi coordinators in cluster

### LINKED ISSUE #5998: [Bug][SystemConnector] NotInTransactionException: Unknown transaction ID because of multi coordinators in cluster
Description：

We run two coordinators/discoveries in our cluster. We try to select system.runtime.queries/system.runtime.tasks and then we hit the bug :

```
presto:runtime> select * from tasks;

Query 20201118_050027_00003_zhiwe, FAILED, 2 nodes
Splits: 18 total, 1 done (5.56%)
0:00 [7 rows, 1.74KB] [132 rows/s, 32.9KB/s]

Query 20201118_050027_00003_zhiwe failed: Unknown transaction ID: 169edb6a-87a8-4ecb-a741-7a64d640f0e9. Possibly expired? Commands ignored until end of transaction block



2020-11-18T13:00:27.553+0800	ERROR	remote-task-callback-9	io.prestosql.execution.StageStateMachine	Stage 20201118_050027_00003_zhiwe.1 failed
io.prestosql.NotInTransactionException: Unknown transaction ID: 169edb6a-87a8-4ecb-a741-7a64d640f0e9. Possibly expired? Commands ignored until end of transaction block
	at io.prestosql.transaction.InMemoryTransactionManager.getTransactionMetadata(InMemoryTransactionManager.java:257)
	at io.prestosql.transaction.InMemoryTransactionManager.getOptionalCatalogMetadata(InMemoryTransactionManager.java:191)
	at io.prestosql.metadata.MetadataManager.getOptionalCatalogMetadata(MetadataManager.java:2139)
	at io.prestosql.metadata.MetadataManager.getSystemTable(MetadataManager.java:385)
	at io.prestosql.connector.system.MetadataBasedSystemTablesProvider.getSystemTable(MetadataBasedSystemTablesProvider.java:54)
	at io.prestosql.connector.system.DelegatingSystemTablesProvider.lambda$getSystemTable$1(DelegatingSystemTablesProvider.java:59)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.connector.system.DelegatingSystemTablesProvider.getSystemTable(DelegatingSystemTablesProvider.java:63)
	at io.prestosql.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:70)
	at io.prestosql.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_unknown____20201118_045911_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Screenshots:

image

image

### PR DESCRIPTION
**Pull request by yangruochen**
fix #5998

### CODE REVIEW

**Comment by yangruochen** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our [Contributor License Agreement](https://github.com/prestosql/cla/raw/master/Presto%20Foundation%20Individual%20CLA.pdf), and we don't seem to have you on file. In order for us to review and merge your code, please submit the signed CLA to [cla@prestosql.io](mailto:cla@prestosql.io). For more information, see https://github.com/prestosql/cla.

Ok, thanks, I have sent this mail.

**Comment by findepi** [comment]
I don't know whether this is the right approach or not -- i will defer to @dain on this -- but did you consider trying to add a test for this?

**Comment by yangruochen** [comment]
> I don't know whether this is the right approach or not -- i will defer to @dain on this -- but did you consider trying to add a test for this?

OK, I try to add a backup coordinator in DistributedQueryRunner if possible.
I have already runned a multi coordinator/discovery presto cluster (a normal coordinator and a backup coordinator) in our company. And I added a new Protocol for presto jdbc with a failover feature. Everything looks like ok except this bug.
I think that when we run this query, CoonnectorManger will add MetaDataBasedSystemTablesProvider to coordinator.

        if (nodeManager.getCurrentNode().isCoordinator()) {
            systemTablesProvider = new DelegatingSystemTablesProvider(
                    new StaticSystemTablesProvider(connector.getSystemTables()),
                    new MetadataBasedSystemTablesProvider(metadataManager, catalogName.getCatalogName()));
        }
        else {
            systemTablesProvider = new StaticSystemTablesProvider(connector.getSystemTables());
        }

And the Distribution of QuerySystemTable is ALL_COORDINATORS, the Distribution of TaskSystemTable is ALL_NODES.

And when it deliver to another coordinator. The MetadataBasedSystemTablesProvider will getSystemTable, and check the transactionId, the backup coordinator haven't this transactionId  and hit the bug.

We just change getTransactionMetadata(transactionId) to tryGetTransactionMetadata(transactionId) and filter the situation of None, and the problem is resolved.
 
I'm a newer in presto, so if I have some error, please correct me. @findepi

**Comment by yangruochen** [comment]
hi @dain ,can you review this pull request for the bug from presto coordinator HA if possible?

**Comment by dain** [comment]
After a lot of digging and discussion with @electrum, I think we want another fix.

This PR directly fixes the issue of `Metadata.getSystemTable` throwing a `NotInTransactionException` by instead making that method return `Optional.empty()`.  This also changes all methods in `MetadataManager` that call `getOptionalCatalogMetadata` to function as if the catalog did not exist.  So after this change when working with `MetadataManger` using a session from another coordinator, most methods will pretend as if no catalogs exist. I'm not sure of the impact of a change that broad, and I'm not sure that is something we want at all.

Instead, I worked out #6237 with @electrum.  This PR addresses a problem much farther up the error stack `MetadataBasedSystemTablesProvider.getSystemTable`.  The problem with this code is it attempts to access metadata without verifying if the session if from the local coordinator. The #6237 simplifies this code (there are other issues) and fixes the core issue.

I'm going to close this PR for now.  If you want to discuss further, you can reopen it, or ask on the liked issue or the new PR.

Thanks for working on this.

**Pull request closed without merging**
